### ISSUE TITLE
Dividend data inconsistencies for symbols

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#1015]
The following list will be updated as I find more things:

MGEE: ex day is 30/5 and not 31/5 like the API say

CBSH: has some zeroes in 2018 and 2016 and maybe more and duplicate dates

BF-B: Returns nothing even though it has dividend history (same for other symbols with -/. in the name like jw.a/jw-a

NJR: Mar 11th dividend should be 0.225 and not 0.45 as it came AFTER the split (adjustable dividend is irrelevant here) http://investor.njresources.com/stock-information/dividends-splits

XBI: div history is so erroneous that I don't know where to begin :)

SPLB: lots of duplicates in 2018 and maybe other problems.

SPYD: lots of duplicates in general

MRRL: no div history at all

GRX has only one div history while there is much more

It's been a week since I reported these issues, how long it takes for the data provider to engage back?

**Comment by evancarter-iex** [comment]
@Amosss We are reaching out to them again. Thanks for your patience

**Comment by evancarter-iex** [comment]
@Amosss 

MGEE fixed
CBSH The zeros and duplicates are related to stock dividends as the company announced cash and stock dividends on the same day
NJR Fixed
XBI Fixed
SPLB Fixed
SPYD Fixed
MRRL & GRX Ill look into why these dont have anything.

**Comment by Amosss** [comment]
Thanks a lot!

CBSH: Not sure I understand what do you mean, here is the history for CBSH: https://www.gurufocus.com/stock/cbsh/dividend

XBI: The last div from 2019-03-15 is zero.

BF-B: Returns nothing even though it has dividend history (same for other symbols with -/. in the name like jw.a/jw-a. Not sure if - should be a dot in the API

**Comment by evankeech** [comment]
Hi IEX,

I have a number of ETFs where the dividend yield is not being properly reported. Of note, all of these ETFs (and ETNs) worked fine with the old IEX non-cloud API.  Some of these are obscure, but some of these are the largest ETFs in their class (VTI, BND, SPY...).  

VTI
VEU
SPTM
SPDW
SPEM
SPSM
ITOT
BND
SPAB
AMZA
SMHD
CEFL
MORL
BDCL
USOI
SJNK
SPTS
MRRL
NEAR
FLRN
JPST
YYY
REM
NEA
HYMB
SPY
SDIV
SRET

Please help!  Thanks!

**Comment by Amosss** [comment]
I just updated the list and noticed that all previous still have problems, any update on these ones?

**Comment by evankeech** [comment]
Thanks for the update. Unfortunately, none of the ETFs/ETN's on the above list are reporting the dividend yield.  I know the code works for three CEFs, because FFC, NZF and MHD do report the dividend yield correctly.  Here is my code used to call the API:

"https://cloud.iexapis.com/stable/data-points/" & ticker & "/dividendYield?token=pk_......"

Also, the example tests/calls from the IEX cloud page don't report the dividend yields correctly.  Using VTI as an example, with this API call for "ttmdividendrate" 

https://cloud.iexapis.com/stable/data-points/VTI/TTMDIVIDENDRATE?token=pk_.......: 

returns "Not found" in the browser.  Browser is Chrome Version 74.0.3729.169 (Official Build) (64-bit).

The API calls used in the documentation (ttmdividendrate, dividendYield) still don't seem to be working...

**Comment by kotarofujita** [comment]
The ETF list provided by evankeech is also an urgent issue for me. Is there any ETA on when and if this may get fixed?

Thx!

**Comment by kotarofujita** [comment]
Getting some reports of these fund related dividends not coming back. So add to the list:

OPP
USA
GAB
GOF
QYLD

**Comment by evancarter-iex** [comment]
@evankeech We are looking into the dividend yield issue.

**Comment by kotarofujita** [comment]
any update of this issue?

**Comment by evankeech** [comment]
This is still an open/unresolved issue for me.  None of the test code, even through the IEX website is reporting the "ttmdividendrate" as it should for the ETFs/ETNs listed above.

**Comment by TedMN** [comment]
I am also very interested in seeing ETF dividend history and upcoming dividend coverage increasing.  Any update?

**Comment by evancarter-iex** [comment]
@TedMN @kotarofujita @evankeech 

@theofficejackpot  
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.

**Comment by karthik448** [comment]
I see 0 being returned as dividend amount for some popular US ETFs even now - QYLD, RYLD, SCHD, SDIV
