### ISSUE TITLE
[Data] URL to pull annual dividend rate

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#1043]
**Clearly describe the data problem**
I have a Google Sheet that has formulas used to pull in the dividend rate for my stocks.  That formula/URL is no longer working.  I'm assuming it has been shut down now with the move to the Cloud API.  I'm wondering if there is a URL that will give me just the annual dividend amount just like my old URL.  I do have a Cloud API account with tokens.

**Data URL (The URL you used to access the data without your token):**
Old URL: https://api.iextrading.com/1.0/stock/ABBV/stats/dividendRate

**What time did the problem occur (including timezone)?**
June 18, 2019

**What is the expected behavior?**
Get the annual dividend rate with a single API call into my Google Sheet.

**What are the steps to reproduce**
Plug the URL into the formula to get the dividend rate.

**Your environment (e.g. browser, OS, API version, language):**
Firefox, Windows 10, Cloud, English

**Additional context**

**Comment by McQgit** [comment]
@dmikester1  Perhaps evan or someone else will provide better answer.  But, it seems you should be able to use the ttmDividendRate from the `stats` endpoint (named Key Stats in the docs) along with the `importdata `function in google sheets as described in the section at the link below.  It's just after the Excel explanation:
[]https://iexcloud.io/docs/api/#excel-how-to

I didn't test this myself but these were designed to do what you describe.

**Comment by derekg52** [comment]
The old endpoints were shut down.  You need to be using the cloud API now with your token.

On a related note - the rates are inconsistent, ETFs tend to lack the value.  On the old IEX api platform the rate was also current and not TTM.  It'll miss the modified rates when companies announce increases.

**Comment by dmikester1** [comment]
Just looking at this now.  @McQgit the ttmDividendRate is the "Trailing twelve month dividend rate per share" which is not at all what I want.  I want the annual dividends based on the latest known dividend payment.  So for ABBV the latest dividend payment is $1.07 and it pays quarterly, so the annual dividends for ABBV is $4.28.  I would think this would be a fairly standard data point related to dividends.  Otherwise I'm going to have to get my hands dirty in the Sheets script code to calculate the annual dividends manually which doesn't sound like a ton of fun.

**Comment by McQgit** [comment]
@dmikester1  You are describing what can be called the 'forward dividend yield' or the 'indicated yield'.  Those are the terms more properly used to describe the annualized rate based on the most recent.  You are correct in describing that as not a lot of fun.  This is only meaningful with stocks that pay consistent amounts with occasional changes (like annual increases).  Many US stocks do pay this way but not all of them.  

Mutual funds, ETFs, REITs and so on don't pay like that so their indicated yields are less, well, indicative.

Non-US stocks (I'm thinking UK and Euro) pay highly varying amounts often as an interim and final.  Trying to annualize the most recent is nearly useless in these cases and you will see many free data providers with crazy yields as a result.

To calculate the indicated yield, you need to know how many dividends are paid per year.  Again, many US stocks pay quarterly but other frequencies do occur and will occur often for funds, non-US, and so on.

So, TTM may not be what you want, but, it is the most consistent across all symbols.

That said, for my own analysis I look at both TTM and the indicated.  Deriving a useful indicated yield across the wide patterns is not trivial.  I look at the dividend history to derive the number per year.  Note tricky situations occur like companies sometimes make 3 payments in a year and sometimes 5 if switch from Dec to Jan for one payment but they are still a quarterly payer for indicated yield purposes.  And, sometimes dividend history is just wrong (all sources I've used in 10 years have errata).  And, well, other quirks.  Some dividend sources identify the payment frequency but this is rare - which is why I derive it myself.

**Comment by dmikester1** [comment]
Thank you for the info.  I know that IEX does provide the payment frequency in their 'dividends' call.
![image](https://user-images.githubusercontent.com/8491610/61793597-1bfa1100-ade5-11e9-8ca6-1e3e95fb3dd5.png)
I am going to spit out the latest dividend amount from that call.  Then spit out a number in the next cell either 4, 12, 2, or 1 depending on what that "frequency" returns and just multiply them into the third cell.  Thank you again for your help.

**Comment by McQgit** [comment]
@dmikester1 YW.  It's nice IEX do that.  I aggregate dividend data from multiple sources to minimize errata.  And, most don't identify frequency so I need to derive it.  

Hope IEX dividend data is reliable enough for you - it wasn't very good earlier this year.  I've started using their upcoming-dividends endpoint recently and that's looking ok so far - hopefully that bodes well for their dividend data in general.

**Comment by McQgit** [comment]
@dmikester1  Oh, and watch for special dividends too - not just 1,2,4,12.  And, non-cash dividends too - in the upcoming-dividends they show w/out a currency but the amount is the number of shares issued so ...  (I don't remember what the frequency flag said - I think maybe just 'Stock').

**Comment by dmikester1** [comment]
@McQgit That's cool to hear that you have done some of the same things I have.  Can I ask if you are building an app/website or just collecting the data for your own portfolio tracking?  What are some of the other sources you are aggregating data from?  I've been trying to write scripts to scrape data automatically from Seeking Alpha and Nasdaq.  And then I also found the API for Alpha Vantage which looked pretty promising until I quickly hit their limit for their free plan.  I'm working on two different things; an app/website idea and then also my own portfolio tracking inside an elaborate Google Sheet.

**Comment by McQgit** [comment]
@dmikester1  I do it for myself.  I built my own website, charts, and so on - yeah - lots of work :)

I collect dividend data for several purposes - historical charting of yields, change alerting, and current snapshot.  For snapshot, I care about ttm and indicated yields from the most recent past dividend and any announced dividend. 

I have a variety of sources for these purposes and it's frankly kind of messy.  I built my own api on my own server with 'wrappers' around other api or scrapes.  This isolates the retrievals from the web app itself.  I've lost track of how many data sources I've used over the years - they are sometimes good for a year or two and then falter.  Nasdaq used to be great but then limited history and got too erratic.  I still use them as a backup source for announcements.  My primary source for announcements and recent history (2Y) has just recently gotten erratic and is missing key dividends.  I won't mention their name as I have special permission to scrape which otherwise is violation of their terms.  I subscribe to their site in consideration.  I have just started using IEX upcoming-dividends for announcements.  I use WSJ daily announcements as a backup source as well.  Everything I gather I add to my personal history for my own holdings.

Long-term historical data I get from Sharadar via Quandl.  It's a paid service which provides me financials, EOD pricing, and dividend history.  It's fairly reliable except includes some non-cash dividends which then shows as a blip on my chart.  I got tired of free service scraping and have using Sharadar for a couple years now.  Their financials are pretty reasonable and good support correcting the occasional errata.

Scraping is problematic although I still rely on it some.  Websites will reformat their html and/or their urls.  Or, introduce scraper blockers.  Or become erratic.  Which is partly why I aggregate in case one goes away I don't have to hurry to replace it or adjust my code.  Seems to always happen when I'm traveling - of course.  Aggregating has the added benefit of better quality data as sources will occasionally make a mistake.

**Comment by dmikester1** [comment]
I have a good guess about which site does not allow scraping via their terms. :)

So I was playing around with this some more tonight, and I finally got it!!  I am posting a screenshot to show what I did.  I am using formulas getting data from IEX to calculate all the columns based off of column 1.
![image](https://user-images.githubusercontent.com/8491610/62002250-b0a28e80-b0c5-11e9-943e-004ad6cfc1ab.png)

**Comment by McQgit** [comment]
I assumed you'd get it working as you described earlier.  It's fine if you are familiar with the stocks in question and they have reliable patterns.  Just don't try that method for DEO, EEM, or NPK as some examples. 

PS: I doubt very much you'd guess the site I didn't name :)

**Comment by mickeyjain26** [comment]
Hey @McQgit  & @dmikester1 
So i am doing something similar, I ended up using the following function:
https://cloud.iexapis.com/stable/stock/AAPL/dividends/1y?token=pk_xxxx 
I am getting the last 4 dividends and wrote a function to get the frequency from the last one and then multiply both to get the annual dividend. 

However, not sure if you guys saw an email from iex around 15th Jul that mentioned Dividend and/or split prior to the last reported data wont be available to start plan(free tier) from 1st August.

Do you guys think this method will continue to work from 1st August ?
