### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by SaratchandraPeddinti** [iexg/IEX-API#1055]
**Clearly describe the data problem**
Hi There,
I'm using the following Data URL to get the stock details. It was working till 1 week back.
However, I started getting "Forbidden" error recently. This is a open data URL and worked without passing any token or authentication details.

**Data URL (The URL you used to access the data without your token):**
https://api.iextrading.com/1.0/stock/market/batch?symbols=pnw&types=quote

**What time did the problem occur (including timezone)?**
Not applicable, i.e., all the time.

**What is the expected behavior?**
The Data URL should return the stock details.

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**
Browser: Chrome, Internet Explorer;
Language: javascript; typescript

**Additional context**

**Comment by trendwithin** [comment]
@SaratchandraPeddinti Arrived here due to similar issue.  You may want to take a look here: [IEX Update](https://iextrading.com/developer/#sunset-schedule) There have been some updates to their services due to their data relationships with 3rd party vendors and now looking like an api key is going to be required moving forward.

**Comment by evancarter-iex** [comment]
@SaratchandraPeddinti @trendwithin Yes, the old api was sunset in June per our announcement a while ago. Please use https://iexcloud.io going forward.
