### ISSUE TITLE
[Data] Lots of errata in upcoming-dividends

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#1072]
**Clearly describe the data problem**
The market/upcoming-dividends response includes many erroneous items

**Data URL (The URL you used to access the data without your token):**
/stock/market/upcoming-dividends?format=csv&token=TOKEN

**What time did the problem occur (including timezone)?**
Samples below from response at Thu Jun27 at 8:50am eastern

**Details of data problem**
I have attached 3 xlsx reports of different categories of data:

Errata1 has 20 lines of past dividends which should not be in an upcoming-dividends list.  They have zeros for exDate and recordDate but their paymentDate is well in the past.

Errata2 has 121 lines with impossible combination of dates.  Likely the paymentDate and exDate columns have been swapped as the paymentDate precedes the exDate.  Further, the paymentDates for all of these are 6/14 so should not be in an upcoming-dividends list - even if that date is actually the exDate.

Errata3 has 20 lines with zeros just for exDate.  All but one have declaredDates of 6/26 so should appear in upcoming-dividends but just are missing exDate.  One of the lines has 6/5 for declaredDate and 6/24 as paymentDate so has past and doesn't belong in upcoming.

[IEX Errata1.xlsx](https://github.com/iexg/IEX-API/files/3335464/IEX.Errata1.xlsx)
[IEX Errata2.xlsx](https://github.com/iexg/IEX-API/files/3335465/IEX.Errata2.xlsx)
[IEX Errata3.xlsx](https://github.com/iexg/IEX-API/files/3335468/IEX.Errata3.xlsx)

**Comment by theofficejackpot** [comment]
Any eta on this? What other/backup data sources do people use for their clients when situations like this happen? My users won’t tolerate this :-(

**Comment by theofficejackpot** [comment]
I have been looking at the data where this is mixed up, and I think what has happened is the ex-div date and the payment date are simply reversed in many cases.

I am going to try to reverse the two in my downstream process when exdiv > payment date.

**Comment by McQgit** [comment]
@theofficejackpot Yeah, that's what I've done too.  I have my own api layer around all my external data sources for this purpose.  I was more annoyed by having to pay message credits for expired 'upcoming' data but the cost is fairly small so not a big priority.

**Comment by evancarter-iex** [comment]
@McQgit 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
