### ISSUE TITLE
IEX Cloud Reports Inconsistent Closing Date for Specific Equities - Re Opened

### ISSUE THREAD

**Issue by GraceRg** [iexg/IEX-API#1074]
**Clearly describe the problem**
I am re-opening this issue and attaching the results of a query that will clearly demonstrate the difference in timestamps between two securities (O and AINV). I do not believe this is a matter of 'timezone conversion' as the closeTime stamps are clearly different for the two equities.

Please do note that I used the batch endpoint to retrieve the results

**What time did the problem occur? (with timezone)**
This query was run on June 28, 2019 at 07:19AM (Eastern)

**What is the expected behavior?**
The closeTime for both equities should have been for June 27, 2019, shortly after 16:00 Eastern.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, MacOS/Windows/ V1, PHP

**API URL (if applicable)**
https://cloud.iexapis.com/V1/stock/market/batch?types=quote,dividends&symbols=ainv,o&token=MY_KEY

**What are the steps to reproduce the bug?**
Executed the API call above

**Additional context**
[2019.06.28 0719 API Results.txt](https://github.com/iexg/IEX-API/files/3338959/2019.06.28.0719.API.Results.txt)

**Comment by McQgit** [comment]
@GraceRg Yes, the time stamps are different and I'll leave it to the IEX staff to comment on why AINV has an 11:31pm close time in your example.  Your O example shows 4:02pm which is more typical.

But, did you find that php timezone info I provided earlier helpful at all?  I ask because in that issue you complained that some close timestamps were for the day after the expected close.  In this current example, both O and AINV are the same day.  So, I'm curious whether you were seeing ~11:30pm timestamps the other day but now know your php date handling was wrong.  Or, whether the timestamps you saw the other day were after midnight.  I'm curious for my own reasons but IEX may find that helpful to know too.  Thanks.

**Comment by evancarter-iex** [comment]
This is most likely due to the data issue with our data provider on Friday. Let us know if it reoccurs today.

**Comment by GraceRg** [comment]
@McQgit , I appreciate the insight. I do use GMT timestamps rather than EST/EDT timestamps for a variety of reasons. That said, I still believe the difference in 'closeTime' between the two listed equities is actually a data issue (as commented by Evan).

@evancarter-iex , I ran the same request on Tuesday morning at 06:48 (Eastern), 10:48 (GMT) and found the issue is still present for the 4 specific equity shares (AINV, GDV, JQC and MCC). Please note that the closeTime for these shares is reported several hours (rather than a few minutes) after 16:00 Eastern (20:00 GMT) and that the prices for the remaining 250 (+/-) equities and funds are reported immediately after the 16:00 close.

Please let me know if I can provide additional information for your diagnostics. 
[2019.07.02 0648E API Results.txt](https://github.com/iexg/IEX-API/files/3349709/2019.07.02.0648E.API.Results.txt)

**Comment by evancarter-iex** [comment]
This is fixed. Marking as such.
