### ISSUE TITLE
[Data] Missing previous & upcoming dividend info

### ISSUE THREAD

**Issue by marekk657** [iexg/IEX-API#1080]
**Clearly describe the data problem**
Some companies dividend data is incomplete. 
1) Upcoming dividends **not provided**.
2) Dividends that were payed or announced within last two months are **not provided**.

Two examples companies with examples for this ticket: BLK, LOW

**Data URL (The URL you used to access the data without your token):**
1) https://cloud.iexapis.com/stable/stock/LOW/dividends?token=TOKEN
2) https://cloud.iexapis.com/stable/stock/BLK/dividends?token=TOKEN&range=ytd

**What time did the problem occur (including timezone)?**
Now

**What is the expected behavior?**
1) https://cloud.iexapis.com/stable/stock/LOW/dividends?token=TOKEN
Should show upcoming dividend.
record with: declared date of 31.05.2019, record date of 24.07.2019, pay date of 07.08.2019

2) https://cloud.iexapis.com/stable/stock/BLK/dividends?token=TOKEN&range=ytd
Last dividend announcement was at 23.05.2019 but endpoint doesn't provide any related data for with.

**What are the steps to reproduce**
Query provided URL-s.

**Your environment (e.g. browser, OS, API version, language):**
API - beta & stable (checked both)

**Additional context**

**Comment by marekk657** [comment]
Additional issue that i just found (10.07.2019):
https://cloud.iexapis.com/stable/stock/PG/dividends?token=TOKEN&range=3m
Newest dividend has ex-date of "0000-00-00"

**Comment by mickeyjain26** [comment]
https://cloud.iexapis.com/stable/stock/AAPL/dividends?token=pk_xxxx
doesnt work for AAPl as well.

**Comment by evancarter-iex** [comment]
@marekk657 

@mickeyjain26 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
