### ISSUE TITLE
[Data] /upcoming-dividends for JW.A has symbol wrong as JWA

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#1083]
**Clearly describe the data problem**
The symbol returned in market/upcoming-dividends json for John Wiley and Sons is wrong.  It is returned as JWA but your supported symbol for pricing is JW.A (as it is for various other data providers).  

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/upcoming-dividends?token=X

**What time did the problem occur (including timezone)?**
8:25am Mon Jul1 eastern

**What is the expected behavior?**
Symbol should be JW.A

**What are the steps to reproduce**
Look at json results for /upcoming-dividends.  The dividend for this was:

{"exDate":"2019-07-09","paymentDate":"2019-07-24","recordDate":"2019-07-10","declaredDate":"2019-06-28","amount":0.34,"flag":"Increase","currency":"USD","description":"John Wiley and Sons Hikes Quarterly Dividend 3%","frequency":"Quarterly","symbol":"JWA"},

**Additional Context**
I recognized this one as missing the period, but, I don't see any others in upcoming-dividends that have a period in the symbol so there may be others missing it as well.

**Comment by evancarter-iex** [comment]
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
