### ISSUE TITLE
[Data] Market cap is incorrect for many symbols

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#1106]
**Clearly describe the data problem**

Atlassian (TEAM) shows a market cap of 16B. But the correct value (i.e. check on bloomberg, google, yahoo, and all other credible sources) shows ~32B. The same issue is happening for many other symbols.

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=team&types=quote&token=

**What time did the problem occur (including timezone)?**

July 10, 2019, 2am EDT. Happening for the past week.

**What is the expected behavior?**

The correct data is returned

**What are the steps to reproduce**

Call the data url

**Your environment (e.g. browser, OS, API version, language):**

IEX Cloud

**Additional context**

**Comment by McQgit** [comment]
@mikezliu  Looking at their financial statement, TEAM has both A and B class shares.  Each class makes up about half the total so using just one or the other would give a market cap about 16B.  Further, TEAM is a foreign issuer so files SEC form 20F rather than 10K/10Q of US companies.  So, when you say you've noticed a market cap problem on other symbols, do either of these issues (multiple share classes, 20F filings) also apply to these others?  See SEC Edgar for TEAM:

[]https://www.sec.gov/cgi-bin/viewer?action=view&cik=1650372&accession_number=0001650372-18-000038&xbrl_type=v#

I don't work for IEX, just curious of my own accord.

**Comment by evancarter-iex** [comment]
This is fixed.
