### ISSUE TITLE
[Data] Null returned for open, high, and low on Quote endpoint for OTC stocks

### ISSUE THREAD

**Issue by jewelr** [iexg/IEX-API#1116]
**Clearly describe the data problem**
OTC stocks are returning Nulls fro open, close, high, and low for the quote endpoint 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/potn/quote

**What time did the problem occur (including timezone)?**
12:41 PM
Monday, July 15, 2019 (MDT)

**What is the expected behavior?**
Today's Open 0.079
Day's Range 0.0681-0.079
close should be null now but it's null even after the day is over

**What are the steps to reproduce**
call this https://cloud.iexapis.com/stable/stock/potn/quote

**Your environment (e.g. browser, OS, API version, language):**
Chrome 74

**Additional context**

**Comment by kchima** [comment]
Just to follow up, this is the second time I've encountered this issue. If I call this endpoint right now:
https://cloud.iexapis.com/stable/stock/NDAQ/quote?token=<token>

I get the following response:
`{"symbol":"NDAQ","companyName":"Nasdaq, Inc.","primaryExchange":"NASDAQ","calculationPrice":"close","open":null,"openTime":null,"close":null,"closeTime":null,"high":null,"low":null,"latestPrice":102.64,"latestSource":"Close","latestTime":"July 17, 2019","latestUpdate":1563393600826,"latestVolume":null,"iexRealtimePrice":102.61,"iexRealtimeSize":100,"iexLastUpdated":1563393594014,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":103.29,"previousVolume":664388,"change":-0.65,"changePercent":-0.00629,"volume":null,"iexMarketPercent":0.023758887780057733,"iexVolume":19070,"avgTotalVolume":714900,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":17007961200,"peRatio":32.09,"week52High":104.69,"week52Low":75.48,"ytdChange":0.268895,"lastTradeTime":1563393600826}`

As you can see, several important metrics return null, in particular, close. open, etc. This makes it hard to rely on iex cloud API for my trading algorithm.

**Comment by kchima** [comment]
I anticipate, as last time, that it will be fine tomorrow. However, it should be investigated in the meantime to prevent it from happening again.

**Comment by wnamen** [comment]
I am having the same issues... my API relies on reliable, up-to-date pricing. Unfortunately, I am only receiving None/null in the pricing responses

**Comment by evancarter-iex** [comment]
@kchima @wnamen Please see the email that was sent to everyone several days ago.

**Comment by wnamen** [comment]
@evancarter-iex I found the email you mentioned... I will pay attention to these releases moving forward.

1 suggestion: The update was clear, however, the changes y'all announced were made effective 24 hours later. Need more time than 24 hours to implement a new solution on my end

**Comment by evancarter-iex** [comment]
@wnamen We understand. Unfortunately, our hands were forced by the vendor in this particular case. But we definitely hear your concern on that.

**Comment by kchima** [comment]
#1 I would expect a better error message on my end (IE an unsuccessful response with a message about permissions, not just having "None" for the prices).

#2 this is the second time in a month I am meant to completely re-implement my data script because IEX has been increasingly restricting their product without grandfathering in existing users.

How am I supposed to count on having a reliable long-term trading algorithm running for years when interruptions are this frequent?

No offense, but this is more trouble than it's worth. I think I will have to start using Alpha Vantage across the board, instead of just for historical data.

**Comment by evancarter-iex** [comment]
@kchima As stated previously, this is a vendor issue, not an IEX issue. We don't make these changes lightly, as we believe in making financial data as open as possible. But in this case our hands are tied.  Also be aware that other providers will have to abide by the same terms, since these terms are coming from vendor, not from us.

**Comment by kchima** [comment]
@evancarter-iex Who is the vendor and what are the terms / how did they change? If I re-upgraded to a "launch" account, would I have access to these fields again?

**Comment by kmsteiner** [comment]
I didn't see the email - could you please send it to me or post it? I am getting null on latestVolume as well. Thanks

**Comment by tkramerix** [comment]
I understand, that with recent changes some values return null. But since yesterday for specific quotes at central times during the trading day almost all values return null as well. 
As an example here from the homepage (sandbox) querying on symbol FREL, not even latest price is returned.) 

{"symbol":"FREL","companyName":"Fidelity MSCI Real Estate Index ETF","primaryExchange":"ESaANY cr","calculationPrice":"sip","open":null,"openTime":null,"close":null,"closeTime":null,"high":null,"low":null,"latestPrice":null,"latestSource":"15 minute delayed price","latestTime":null,"latestUpdate":null,"latestVolume":null,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":26.42,"previousVolume":null,"change":null,"changePercent":null,"volume":null,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":261582,"iexBidPrice":27.51,"iexBidSize":102,"iexAskPrice":0,"iexAskSize":0,"marketCap":null,"peRatio":null,"week52High":27.68,"week52Low":22.07,"ytdChange":null,"lastTradeTime":1599391057351}

**Comment by deejaykim** [comment]
Can I get some pointer to the change I need to make it work again? I've been facing the same issue since few weeks ago and I didn't receive any email from IEX Cloud team. I checked the API DOC to see if endpoints changed, but they remain the same. Please help!

**Comment by kmsteiner** [comment]
Hi EvanI need to get data on advancing, declining and unchanged market data, similar tohttps://www.wsj.com/market-data/stocks/marketsdiary  orhttps://www.marketwatch.com/tools/marketsummary?region=usa
Does IEX have this data available?I have found the following:https://api.iextrading.com/1.0/marketas well as https://iextrading.com/apps/market/Can you explain what tapeA, tapeB and tapeC represent in https://iextrading.com/apps/market/   I believe they add up to give volume
https://api.iextrading.com/1.0/market
gives the following data:[ {"mic":"TRF","tapeId":"","venueName":"TRF Volume","volume":1507598087,"tapeA":746237296,"tapeB":275674550,"tapeC":485686241,"marketPercent":0.38429,"lastUpdated":1568918043174}, {"mic":"XNGS","tapeId":"Q","venueName":"NASDAQ","volume":686454785,"tapeA":267269507,"tapeB":132098736,"tapeC":287086542,"marketPercent":0.17498,"lastUpdated":1568918043179}, {"mic":"XNYS","tapeId":"N","venueName":"NYSE","volume":375751647,"tapeA":331311512,"tapeB":24341198,"tapeC":20098937,"marketPercent":0.09578,"lastUpdated":1568918043180}, {"mic":"ARCX","tapeId":"P","venueName":"NYSE Arca","volume":308776234,"tapeA":102477220,"tapeB":120302473,"tapeC":85996541,"marketPercent":0.07871,"lastUpdated":1568918043169}, {"mic":"EDGX","tapeId":"K","venueName":"EDGX","volume":250261249,"tapeA":111457667,"tapeB":54413655,"tapeC":84389927,"marketPercent":0.06379,"lastUpdated":1568918043179}, {"mic":"BATS","tapeId":"Z","venueName":"BATS BZX","volume":229374237,"tapeA":110993704,"tapeB":50057893,"tapeC":68322640,"marketPercent":0.05847,"lastUpdated":1568918043174}, {"mic":"BATY","tapeId":"Y","venueName":"BATS BYX","volume":143164175,"tapeA":74726376,"tapeB":39547459,"tapeC":28890340,"marketPercent":0.03649,"lastUpdated":1568918043147}, {"mic":"IEXG","tapeId":"V","venueName":"IEX","volume":119433809,"tapeA":72765274,"tapeB":11672212,"tapeC":34996323,"marketPercent":0.03044,"lastUpdated":1568918043175}, {"mic":"EDGA","tapeId":"J","venueName":"EDGA","volume":101258133,"tapeA":54163377,"tapeB":19904330,"tapeC":27190426,"marketPercent":0.02581,"lastUpdated":1568918043153}, {"mic":"XCIS","tapeId":"C","venueName":"NYSE National","volume":68125318,"tapeA":37949725,"tapeB":16176258,"tapeC":13999335,"marketPercent":0.01737,"lastUpdated":1568918043043}, {"mic":"XBOS","tapeId":"B","venueName":"NASDAQ BX","volume":61176291,"tapeA":27830340,"tapeB":17697779,"tapeC":15648172,"marketPercent":0.01559,"lastUpdated":1568918043081}, {"mic":"XPHL","tapeId":"X","venueName":"NASDAQ PSX","volume":31432564,"tapeA":10000977,"tapeB":13052068,"tapeC":8379519,"marketPercent":0.00801,"lastUpdated":1568918043083}, {"mic":"XCHI","tapeId":"M","venueName":"CHX","volume":25340082,"tapeA":6119137,"tapeB":13679606,"tapeC":5541339,"marketPercent":0.00646,"lastUpdated":1568918041475}, {"mic":"XASE","tapeId":"A","venueName":"NYSE American","volume":14882765,"tapeA":3682424,"tapeB":9015517,"tapeC":2184824,"marketPercent":0.00379,"lastUpdated":1568918041666}]



    On Wednesday, August 21, 2019, 03:14:01 PM EDT, evancarter-iex <notifications@github.com> wrote:  
 
 
Closed #1116.

**Comment by JKMossCoder** [comment]
Sorry to be late to the party here, but I got involved with IEX after this post, so don't know what the email said. can someone please send me the email? (codeguycs50x@gmaill,com)

**Comment by roytmanD** [comment]
> @kchima @wnamen Please see the email that was sent to everyone several days ago.

pls send me an email too, just did my setup and getting  nulls in some metrics

**Comment by AveryData** [comment]
im still having the same issues. any resolution?

**Comment by timpaine-iex** [comment]
@kmsteiner https://en.wikipedia.org/wiki/National_market_system_plan

**Comment by timpaine-iex** [comment]
@JKMossCoder @AveryData some exchanges have restrictions without additional authorization https://intercom.help/iexcloud/en/articles/2956164-real-time-and-15-minute-delayed-stock-prices
