### ISSUE TITLE
[Issue] News SSE message usage didn't reconcile issue

### ISSUE THREAD

**Issue by gcobcqwe** [iexg/IEX-API#1123]
**Clearly describe the problem**
When I used news SSE to established around 1600 connections( around 79,500 symbols and each 50 symbols create a connection), it reserved around 100,000,000 message usages. After one day, when I stoped it, it seemed that usages didn't reconcile. I compared my logs with IEX message usage. The IEX message usage is much greater than my logs. 
IEX message usage is around 5%  => 100,000,000 messages
Actually, I received around 590,000 messages

**What time did the problem occur? (with timezone)**
2019/07/17 UTC+8

**What is the expected behavior?**
correct usages 

**Your environment (e.g. browser, OS, API version, language):**
I used node v8.10.0 with request library to establish connection

**API URL (if applicable)**
https://cloud-sse.iexapis.com/stable/news-stream?symbols={symbols}&snapshotAsOf={latest_timeStamp_of_ticker}+1&token={token} 

**What are the steps to reproduce the bug?**
Use the API URL above to create around 1600(All IEX symbols / 50 ) connections. After one day, stop all connections and then watch IEX message usage.

**Comment by evancarter-iex** [comment]
@gcobcqwe we deployed something to fix this. If this still an issue please reach out to support@iexcloud.io

**Comment by zeahmed** [comment]
I am having the same issue. Opened 50 connections to News SSE. My machine went down last night. Server should take it as disconnect and reconcile the messages. However, it is still showing message usage while there were 50 connections ON.

I observe that it happens when 50 connection went down at once and IEX server is not able reconcile them. For my case, it happened during sandbox testing.
