### ISSUE TITLE
All pre-market stock quotes return null extended prices and extended percentages such as in extendedPrice 

### ISSUE THREAD

**Issue by yairleisure** [iexg/IEX-API#1128]
As of today, July 18th, I am not receiving any pre-market prices. The related fields such as extendedPrice are always 'null'.

For example, for the request:
```
https://cloud.iexapis.com/stable/stock/aapl/quote?token=MY_API_TOKEN
```

I am getting the following response:
```
{"symbol":"AAPL","companyName":"Apple, Inc.","primaryExchange":"NASDAQ","calculationPrice":"close","open":null,"openTime":null,"close":null,"closeTime":null,"high":null,"low":null,"latestPrice":203.35,"latestSource":"Close","latestTime":"July 17, 2019","latestUpdate":1563393600677,"latestVolume":null,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":204.5,"previousVolume":16866816,"change":-1.15,"changePercent":-0.00562,"volume":null,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":22208559,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":935629618000,"peRatio":16.96,"week52High":233.47,"week52Low":142,"ytdChange":0.282057,"lastTradeTime":1563394524109}
```

**Comment by evancarter-iex** [comment]
@yairleisure Please refer to the email we sent out earlier this week regarding NASDAQ's data policy.

**Comment by yairleisure** [comment]
@evancarter-iex I went through all my emails but didn't find anything. I also couldn't find anything on the website or the docs/knowledge base. Can you please suggest where I can find it or what do I need to do in order to get pre-market and post-market prices?

**Comment by jmoscatiello** [comment]
@yairleisure 
Due to data provider policy, effective Wednesday, July 31, UTP data for Nasdaq-listed stocks will only be available through IEX Cloud if you are on a Launch, Grow, or Scale plan and authorized by UTP directly to continue to receive UTP data. UTP data has already been removed from Start plans. 

Well, Nasdaq controls UTP consolidated delayed stock prices for companies listed on Nasdaq (i.e., UTP, Nasdaq UTP or “Tape C” securities). That means that all 15-minute delayed intraday price data for Nasdaq-listed stocks will be impacted. 

To be clear, IEX Cloud will continue to provide non-delayed intraday data for all stocks when those quotes and trades occur on the Investors Exchange. That’s a lot of data! But you will notice that, for Nasdaq-listed stocks only, some key points, such as the official opening and closing price, as well as pre- and post-market prices (before 9:30 am ET and after 4:00 pm ET), will be missing. Data for non-Nasdaq listed stocks will not be affected. The full list of affected endpoints for Nasdaq-listed stocks is below.
