### ISSUE TITLE
BTA next dividend question

### ISSUE THREAD

**Issue by theofficejackpot** [iexg/IEX-API#1137]
**Clearly describe the data problem**
Why is the ex-Div date 8/1 but the payout date is 7/15? 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/BTA/dividends/next?token=

**What time did the problem occur (including timezone)?**
7/20/2019 1:16pm est

**What is the expected behavior?**
The ex dividend date should be before the payment date

**What are the steps to reproduce**
run the url provided

**Your environment (e.g. browser, OS, API version, language):**
safari macOS

**Additional context**

**Comment by McQgit** [comment]
@theofficejackpot  Already reported (with others) in #1072  (see Errata2 spreadsheet)

**Comment by evancarter-iex** [comment]
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
