### ISSUE TITLE
[Data] Preferred Stocks? WFC.PRN

### ISSUE THREAD

**Issue by theofficejackpot** [iexg/IEX-API#1138]
**Clearly describe the data problem**
I can't figure out how to query preferred stocks such as Wells Fargo preferred stock

**Data URL (The URL you used to access the data without your token):**
https://sandbox.iexapis.com/stable/stock/WFC.PRN/stats?token=
see:
https://www.preferredstockchannel.com/symbol/wfc.prn/

**What time did the problem occur (including timezone)?**
July 20, 2019

**What is the expected behavior?**
I want to get the yield and quote data for preferred stocks

**What are the steps to reproduce**
Navigate to the sandbox url above

**Your environment (e.g. browser, OS, API version, language):**
safari macOS

**Additional context**

**Comment by McQgit** [comment]
Check this out:  []https://iexcloud.io/docs/api/#symbols

Especially, note the `type`

**Comment by theofficejackpot** [comment]
ok, thanks, I see them as WFC-L for example.
but how do I have the dividend history?
https://sandbox.iexapis.com/stable/stock/WFC-L/dividends/1y?token=

reveals no data...

**Comment by evancarter-iex** [comment]
@theofficejackpot  
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
