### ISSUE TITLE
[Data] Missing intraday data

### ISSUE THREAD

**Issue by pathvine** [iexg/IEX-API#1149]
**Clearly describe the data problem**
BYND (7/18/2019) and PTC (7/12/2019) intraday quotes are missing.
ALGN intraday quotes seems to be trading thinner than DIA consistently, that doesn't seem right. 

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/bynd/chart/date/20190718
https://cloud.iexapis.com/stable/stock/ptc/chart/date/20190712

**What time did the problem occur (including timezone)?**
For whole trading day when those data are missing.

**What is the expected behavior?**
The API should return the market minute-by-minute OHLCV quotes for those symbols and dates.

**What are the steps to reproduce**
By Visiting those API listed above.

**Your environment (e.g. browser, OS, API version, language):**
Any

**Additional context**
This seems to be a recurring issue. Is there a script on your quotes server to check for missing backfill? On my side I got a script to check for the daily data integrity, but it is a hassle for both you and me if I keep posting similar issues regarding this.

**Comment by McQgit** [comment]
@pathvine  Those are both Nasdaq listed securities.  Intraday prices for them are impacted by a recent policy change by Nasdaq.  If you are a Start user, those changes are already in place (are you one?).  For other plans, we have until Jul31.  Here's the announcement about it from IEX:

Hello,
Due to data provider policy, effective Wednesday, July 31, UTP data for Nasdaq-listed stocks will only be available through IEX Cloud if you are on a Launch, Grow, or Scale plan and authorized by UTP directly to continue to receive UTP data. UTP data has already been removed from Start plans. 

What does that mean for you? 

Well, Nasdaq controls UTP consolidated delayed stock prices for companies listed on Nasdaq (i.e., UTP, Nasdaq UTP or “Tape C” securities). That means that all 15-minute delayed intraday price data for Nasdaq-listed stocks will be impacted. 

To be clear, IEX Cloud will continue to provide non-delayed intraday data for all stocks when those quotes and trades occur on the Investors Exchange. That’s a lot of data! But you will notice that, for Nasdaq-listed stocks only, some key points, such as the official opening and closing price, as well as pre- and post-market prices (before 9:30 am ET and after 4:00 pm ET), will be missing. Data for non-Nasdaq listed stocks will not be affected. The full list of affected endpoints for Nasdaq-listed stocks is below. 

What if you want to keep receiving this data? 

If you’d like to get authorization to receive this data through IEX Cloud or any other data vendor (Nasdaq UTP's policy applies to all redistributors of Nasdaq UTP data) you’ll need to fill out Nasdaq UTP’s forms and pay the applicable fees, which start at $250 per year (additional Nasdaq UTP fees may apply). When you are approved to receive Nasdaq UTP data, Nasdaq UTP will alert IEX Cloud, at which point access to Nasdaq UTP data via IEX Cloud can be enabled. We are currently working with Nasdaq UTP to add IEX Cloud as an option in the relevant forms. You can find more information on how to get authorization from Nasdaq UTP to receive the data here. 

If you intend to get Nasdaq UTP approval to continue receiving the data, or if you already have a Nasdaq UTP agreement and just need to add IEX Cloud as an approved channel, please email us at support@iexcloud.io. We will do everything we can to help you avoid a disruption in the data you receive through IEX Cloud and will let you know when the forms are ready for you to fill out. 
Please reach out to us with any comments or questions. We look forward to continuing to bring you new data and tools to help you build. 

Joshua Blackburn
Head of IEX Cloud

Affected endpoints for Nasdaq-listed symbols ONLY 
• "Quote”: open, openTime, close, closeTime, delayedPrice, delayedPriceTime,extendedPrice, extendedPriceTime, extendedChange, extendedChangePercent, week52High, week52Low, high, low fields will be null.  
• “Quote”: latestPrice, latestUpdate, latestTime, latestSource, change, changePercent, marketCap, ytdChange will no longer incorporate Nasdaq UTP data but will continue to use Investors Exchange data.  
• “OHLC”: all fields will be null.  
• “Intraday Prices”: all fields prefixed with “market” will be null.

**Comment by pathvine** [comment]
@McQgit Hi Josh, thank you for your quick reply. I am on the launch plan and am able to retrieve intraday quotes for the same tickers and other dates, except the above mentioned tickers + dates combination. Therefore, I think it is a backfill missing issue.

**Comment by McQgit** [comment]
@pathvine  I'm not Josh - just reposting the IEX notice he sent.  Agree it sounds like a backfill issue.  But, note per his email that after Jul31 intraday pricing for Nasdaq stocks will not be available unless you have arrangement with Nasdaq.  So, the method you're using will stop working for those symbols shortly - as I understand it anyway.

**Comment by pathvine** [comment]
@McQgit thanks for clearing that up. I got confused there. For the UTP data, I will have to see how it will really impact me, as I am only concerned with the 15-min delayed quotes during the regular trading hours ans EOD quotes from Nasdaq.

**Comment by evancarter-iex** [comment]
@pathvine Im seeing data for BYND on the date requested. Ill look into PTC but its possible it wasnt traded that day on IEX
