### ISSUE TITLE
[Request] Add 'companyName' to the 'previous' endpoint

### ISSUE THREAD

**Issue by arcasinky** [iexg/IEX-API#1167]
**Is your feature request related to a problem? Please describe.**
No.  Simply an enhancement.

**Describe the solution you'd like**
It would be convenient if the company name were included in the JSON reply for the 'previous' endpoint.

**Describe alternatives you've considered**

In principle, one must send a second request to the 'company' endpoint to obtain the company name attached to a particular symbol.  That endpoint seems broken at the moment...it returns 'Forbidden' regardless of the key that I specify and regardless of the exchange the symbol is listed on.  But this second request could be avoided if the 'previous' endpoint included the company name in its JSON output.

**Additional context**

**Comment by McQgit** [comment]
The /company endpoint works for me.  I know this doesn't speak to your enhancement request but it should work.  I sometimes forget the '/stock/' part for those kind of endpoints.  Although, that gives a 'not found' rather than 'forbidden' for me.  Anyway, could you have made similar typo?  It should be like:
[]https://cloud.iexapis.com/v1/stock/aapl/company?token=(redacted)

As to your enhancement, IEX can count me as a weak vote against.  I don't like the clutter and extra message length for batch /previous requests.  If I need company metadata, I usually need more than just the name.

**Comment by McQgit** [comment]
Oh, did you know you can do something like this?  It avoids the second request you didn't like.

[]https://cloud.iexapis.com/stable/stock/market/batch?symbols=sbux,mcd&types=previous,company&token=(redacted)

Use a single symbol if that's all you want (still use the plural `symbols=` though)
