### ISSUE TITLE
Dividend data availability is hit or miss

### ISSUE THREAD

**Issue by twoinvesting** [iexg/IEX-API#1169]
I'm working on a spreadsheet that looks up dividend amounts. For some reason, it is hit or miss whether these API calls will work. Some stocks work with both, while others only work with the first one.

For example, the call below gets the latest dividend for Macy's:
`https://cloud.iexapis.com/stable/data-points/m/LAST-DIVIDEND-AMOUNT?token=“pk_123456789”`

While this does one does not, returning []:
`https://cloud.iexapis.com/stable/stock/m/dividends?token=“pk_123456789”`

If I use Apple’s ticker symbol, AAPL, both work. Which one of these should I be using? I don’t understand how data is missing from one that is available on the other. 

Google Sheets has trouble with a ton of IMPORTDATA calls so I'm trying to limit those the best I can.

Any suggestions?

Scott

**Comment by evancarter-iex** [comment]
@twoinvesting We are in process of getting this cleaned up for good.

**Comment by duncanmulholland** [comment]
@twoinvesting I have also experienced this issue when using https://cloud.iexapis.com/stable/stock/SYMBOL/dividends?token=“MY_TOKEN_HERE”

For some symbols Dividend info comes back, other symbols it does not, even when the symbol in question has a healthy dividend history stretching back years.

**Comment by evancarter-iex** [comment]
@twoinvesting @duncanmulholland 
@xxx44yyy 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
