### ISSUE TITLE
[Issue] Crypto Quote Data comes up as NotFound

### ISSUE THREAD

**Issue by thinkcodellc** [iexg/IEX-API#1185]
**Clearly describe the problem**
When the crypto quote was invoked using the URL specified in the API doc, it returns as not found.

**What time did the problem occur? (with timezone)**
8 AM CST - 9 AM CST

**What is the expected behavior?**
Returns the right quote information

**Your environment (e.g. browser, OS, API version, language):**
Chrome Browser - Win10 
API v1/stable

**API URL (if applicable)**
https://cloud.iexapis.com/stable/crypto/ETH/quote?token=xxx

**What are the steps to reproduce the bug?**
Invoke the URL for crypto symbols BTC, ETH etc

**Additional context**

**Comment by evancarter-iex** [comment]
@thinkcodellc Hi there, I am seeing quotes working. Can you check again?

**Comment by McQgit** [comment]
I added 'USDT' to the end of your symbols and got the right quote (BTCUSDT).  I only tried this based on their examples in the docs.  I tried using the /ref-data/symbols to get all the correct symbols but the cryptos were not in there so that's a problem.

Careful that ETH is a valid symbol but not for crypto (it's Ethan Allen on the equity exhanges).

**Comment by McQgit** [comment]
@evancarter-iex @thinkcodellc  I had to add USDT to the end of the symbol to get it to work - like ETHUSDT.  Same with BTC.  Careful to note that using just ETH gave a quote for Ethan Allen equity.  But, ETHUSDT was Ethereum.  Example:

[]https://cloud.iexapis.com/stable/crypto/ethUSDT/quote?token=(token)

**Comment by thinkcodellc** [comment]
Thanks for the response @evancarter-iex & @McQgit .  Seeing it now!
