### ISSUE TITLE
Keeping database up to date

### ISSUE THREAD

**Issue by Jacyle** [iexg/IEX-API#1218]
Besides running a daily query on numerous endpoints, like balance sheet, cashflow, income statement, etc..., is there some way to know when to run a query for a particular ticker? maybe using Upcoming Events?

Any suggestions would be helpful.

**Comment by dmikester1** [comment]
I *think streaming might be what you are looking for: https://iexcloud.io/docs/api/#streaming

**Comment by amittleider** [comment]
I think @Jacyle is looking for the Data Points API https://iexcloud.io/docs/api/#data-points. But there is an issue preventing it from doing precisely what you need here: https://github.com/iexg/IEX-API/issues/874.

In your case, since you are only concerned about fundamentals. If you don't have time to wait for a fix on the IEX side, I would recommend saving on your side the results of a call to UpcomingEarnings https://iexcloud.io/docs/api/#upcoming-events , then using that date to know when to query fundamentals again.

**Comment by nickkraakman** [comment]
> I think @Jacyle is looking for the Data Points API https://iexcloud.io/docs/api/#data-points. But there is an issue preventing it from doing precisely what you need here: #874.
> 
> In your case, you are only concerned about fundamentals. If you don't have time to wait for a fix on the IEX side, I would recommend saving on your side the results of a call to UpcomingEarnings https://iexcloud.io/docs/api/#upcoming-events , then using that date to know when to query fundamentals again.

This is exactly what I am doing now, until IEX releases their `Rules Engine`, which should include webhooks that fire when new data becomes available.
