### ISSUE TITLE
[Issue] MACK ex-date have zero

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#1220]
**Clearly describe the problem**
zero ex-date: 

`{"exDate":"0000-00-00","paymentDate":"2017-05-26","recordDate":"0000-00-00","declaredDate":"2017-05-10","amount":0,"flag":"Special","currency":"USD","description":"Merrimack Pharmaceuticals Declares Special Cash Dividend of $140M","frequency":"Other","symbol":"MACK"}`

**What time did the problem occur? (with timezone)**
any

**What is the expected behavior?**
correct date, see: [https://www.nasdaq.com/symbol/mack/dividend-history](https://www.nasdaq.com/symbol/mack/dividend-history)

**Your environment (e.g. browser, OS, API version, language):**
any

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/mack/dividends/next?token=

**What are the steps to reproduce the bug?**
simple http request

**Additional context**

**Comment by evancarter-iex** [comment]
@xxx44yyy 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
