### ISSUE TITLE
[Data] Data mismatch between SIP data and IEX data

### ISSUE THREAD

**Issue by pps83** [iexg/IEX-API#1239]
For example, minute data for AAPL for date=20190603:

```
	{
		"date": "20190603",
		"minute": "09:32",
		"label": "09:32 AM",
		"high": 176.775,
		"low": 176.1,
		"average": 176.48,
		"volume": 4112,
		"notional": 725685.495,
		"numberOfTrades": 46,
		"marketHigh": -1,
		"marketLow": -1,
		"marketAverage": -1,
		"marketVolume": 0,
		"marketNotional": 0,
		"marketNumberOfTrades": 0,
		"open": 176.32,
		"close": 176.74,
		"marketOpen": null,
		"marketClose": null,
		"changeOverTime": 0.0026475166748098435,
		"marketChangeOverTime": -1.0056904832358365
	},
```

note that even IEX data contains some trades for APPL at 9:32am, yet, your API reports that total market had no trades. This is complete BS, `marketVolue`/`marketNumberOfTrades` cannot be less than `volume`/`numberOfTrades`.

**Comment by McQgit** [comment]
Perhaps an IEX person will clarify but I believe this is due to the recent Nasdaq UTP change.  The 'market' fields are official Nasdaq data and since AAPL is listed on their exchange it is subject to this.

See the IEX FAQ:
[]https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud

The FAQ doesn't say the 'market' fields are not available for the 'quote' endpoint, but, the 'intraday' endpoint description does so I presume that means 'quote' is the same.  Again, perhaps the IEX folks can clarify.

The FAQ describes what you need to do to get Nasdaq UTP data through IEX and what alternatives work without that.  It's a good read if you haven't seen this yet.

**Comment by pps83** [comment]
I loaded AAPL history a couple of month ago before that Nasdaq UTP mess came to effect. Also, that quoted minute `09:32 AM` when market data is 0, There are a few other minutes like that, other than that market data is present in that file.

**Comment by kmdguy** [comment]
I recently signed up for IEX's LAUNCH plan. I'm working on a simple app but now I'm finding that I cannot get at the Nasdaq datapoints I need. Am I to understand that I have to fill out/sign all of the UTP stuff and pay $24/month+ to access this along with my IEX fee? I've tried emailing IEX numerous times but I never get a reply.

**Comment by evancarter-iex** [comment]
@pps83 is this an ongoing issue or just dealing with that date?

@kmdguy please email us at support@iexcloud.io if you need to reach out to us (its possible stuff got lost in the shuffle). https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud should hopefully answer your questions.

**Comment by pps83** [comment]
> @pps83 is this an ongoing issue or just dealing with that date?

I've seen that a few times that some minutes are randomly missing here and there for different stocks. That specific stock/data-time is just an example. Maybe IEX-cloud should run some checks on the data they they serve to verify for obvious flaws like the one I pointed out where overall market volume is zero or less than volume on IEX itself.

**Comment by evancarter-iex** [comment]
@pps83 Thanks for the response. We have moved the intraday data to a new platform that should help alleviate the issues with randomly missing minutes. The market volume and IEX volume come from two different data sources so in theory there could be data not reported to the SIP in time for that minute etc. But I will look into seeing if it has happened recently
