### ISSUE TITLE
About Dividends API "frequency", "flag" field

### ISSUE THREAD

**Issue by HHEntertainment** [iexg/IEX-API#1256]
Hello. I'm a paid user of IEX Cloud.

I want to know the all list of what values ​​can be returned in the frequency, flag field in the Dividend Information API.

Also, the frequency field is often empty, what does this mean?

Please explain clearly.

**Comment by McQgit** [comment]
@HHEntertainment  I agree it would be nice to have formal docs for this.  Until then, these are the values I've discovered from using the /upcoming-dividends endpoint:

First, I've noticed if the announce date, flag, and frequency are all empty then it is a dividend for an ETF.  

Otherwise, 

Flag will be one of:
`'Special','Interim','Resume','Increase','Decrease','Initiation','No Change','Stock'`

Frequency will be one of:
`'Quarterly','Semi-Annual','Annual','Monthly','Other'`

I presume these values are the same as for the /dividends endpoint.

**Comment by HHEntertainment** [comment]
@McQgit 
Thank you for your reply.

And one more question!
How do I know if that dividend is a regular dividend or a special dividend?
Because I want to show in my app just regular dividend information.

But if I think, many things(stock distribution, regular dividend, special dividend and so on..) are mixed..

Thank you again and have a nice day!

**Comment by McQgit** [comment]
@HHEntertainment  

Oh, one thing about flag is after "No Change" you will have further description so just look at beginning.  For example, you'll see "No Change QoQ" (quarter over quarter)

To avoid specials, you could skip flags of Special or Stock.  

You are right, there are sometimes very odd distributions so I create my own errata report for combinations I wasn't expecting.  Then I fine-tune my logic from that.  You might want to try the same using the /upcoming-dividends endpoint as that will show a lot of dividends.  Just careful with its weight cost - it can get expensive.

**Comment by McQgit** [comment]
@HHEntertainment 
A note to future searchers - all of the above info is now incorrect.  IEX switched to a new dividend data provider the week of Oct21 2019 and the returned data is now very different.

**Comment by look4parker** [comment]
The dividend frequency and description data seems to be returning as a jumbled string.  i.e. expecting frequency to return "quarterly" but received "lrayuetrq" (all the letters are mixed up)

**Comment by McQgit** [comment]
@look4parker In the sandbox much of the data is randomized.  Try production api
