### ISSUE TITLE
[Data] JPM has two dividend entries for same ex-date

### ISSUE THREAD

**Issue by WillTron** [iexg/IEX-API#1260]
**Clearly describe the data problem**
The /dividends/ endpoint for JPM has two entries for exDate "2019-10-03". The values for the keys are the same for the two entries with the exception of declaredDate, flag and description. JPM did announce a dividend increase in June from 0.80 to 0.90 to take effect during the third quarter so the first entry with the "increase" flag and description appears correct, but the second array flag value is incorrect -- it should NOT be "No Change QoQ".

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/market/batch?symbols=jpm&types=dividends&token=my_token

**What time did the problem occur (including timezone)?**
9/27/19 5 pm PST USA, but it had the same output several days ago also.

**What is the expected behavior?**
To not have conflicting dividend key values for the same ex-div date. Not sure what the correct behavior should be, but what is displayed seems incorrect. it's also possible I am misunderstanding how the dividend endpoint is supposed to work.

**What are the steps to reproduce**
Run api url in browser

**Your environment (e.g. browser, OS, API version, language):**
latest Chrome, Win10 Pro, IEX Cloud v1, Launch Plan

**Additional context**
```
{
  "JPM": {
    "dividends": [
      {
        "exDate": "2019-10-03",
        "paymentDate": "2019-10-31",
        "recordDate": "2019-10-04",
        "declaredDate": "2019-06-27",
        "amount": 0.9,
        "flag": "Increase",
        "currency": "USD",
        "description": "JPMorgan Chase & Co. Hikes Quarterly Dividend 12.50%",
        "frequency": "Quarterly",
        "date": "2019-09-28"
      },
      {
        "exDate": "2019-10-03",
        "paymentDate": "2019-10-31",
        "recordDate": "2019-10-04",
        "declaredDate": "2019-09-17",
        "amount": 0.9,
        "flag": "No Change QoQ",
        "currency": "USD",
        "description": "JPMorgan Chase & Co. Declares Quarterly Dividend of $0.90 Per Share",
        "frequency": "Quarterly",
        "date": "2019-09-28"
      }
    ]
  }
}
```

**Comment by evancarter-iex** [comment]
@WillTron I will look into this but we are looking to expand our dividend data since we continue to have problems here.

**Comment by evancarter-iex** [comment]
@WillTron 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is now correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
