### ISSUE TITLE
[Data] Dividends NAC

### ISSUE THREAD

**Issue by lars670** [iexg/IEX-API#1286]
By coincidence we noticed that no dividends at all are present for NAC.
Why is this?
As you can see on enclosed Yahoo chart, this is an instrument wiht a lot of Dividend payments

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/NAC/dividends/1y?token=pk_XX

**Comment by evancarter-iex** [comment]
@lars670 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket, since the data is now there. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
