### ISSUE TITLE
[Data]

### ISSUE THREAD

**Issue by emmette** [iexg/IEX-API#1322]
**Clearly describe the data problem**

I’m trying to efficiently bulk request 5y of historical charts data for ~8k symbols using the v1 chart endpoint, say running from 10-1-2009 to 10-1-2014.

In the endpoint documentation there does not seem to be a way to specify a start date using the 5y range.

Given these limitations, what is the most reasonable call to get data over a large chunk of time in a specified date range?

**Comment by McQgit** [comment]
@emmette  Perhaps someone else may know a more efficient way.  But, have you reviewed the message weighting costs even if you could retrieve the time frame you describe? 

For example, 5 years of daily prices would have the message weight roughly:
250 trading days/year * 5Y * 10 weight/day * 8000 symbols = 100,000,000 messages

If you had to retrieve the most recent 10Y and discard the latest 5Y to get the data you describe, double the above.

The docs for /chart say if you retrieve only adjusted close (rather than ohlcv) then the weight cost/day is only 2 units, not 10, so adjust accordingly.

See their calculator here:
[]https://iexcloud.io/calculator/

And the weighting topic here:
[]https://iexcloud.io/docs/api/#how-messages-work

**Comment by emmette** [comment]
Thanks McQgit!

I'm less concerned with message weighting as I can always filter & more concerned with a reasonably efficient way to requesting large blocks of time from a given endpoint.

The other option I’ve explored is to use the market/batch? endpoint to at least request chart data for a batch of 100 symbols (rather than iterating through 5 years of dates x 8k+ symbols), but this fails with a “The API key provided is not valid.” See below url. The same API key works on other calls.

My best guess on this approach is that the market/batch? endpoint does not support specific dates in the range.

Data URL (The URL you used to access the data without your token):

https://cloud.iexapis.com/v1/stock/market/batch?symbols=ZROZ,ZS,ZSAN&types=chart&range=20191109&token=<token removed>

**Comment by McQgit** [comment]
@emmette I couldn't get range=yyyymmdd to work either. 

I vaguely remember seeing something about needing to be a Scale account to get lots of minute-bar data in /chart.  So, when using range with a specific date I tried adding chartByDay=true and chartCloseOnly=true for just closing prices.  But, that didn't work either.  I always got the message about invalid api key for my (well-used) token when using a specific date with range.  Perhaps my memory is wrong about the Scale account.

I am able to use range=max for 15Y of daily history.  Not as efficient of course and uses more messages.

You may be best served by emailing IEX support on this.  The docs say they are evolving the /time-series endpoint to replace /chart.  Perhaps it's due soon.

**Comment by MattAbar** [comment]
I would also like the ability to specify a start/end dates for a price query.

**Comment by timpaine-iex** [comment]
time-series
