### ISSUE TITLE
Declared dividends not being reported

### ISSUE THREAD

**Issue by CraigerBrau** [iexg/IEX-API#1331]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the data problem**
I have not seen any newly declared dividends reported.  GPC, KSS, FL, CTL, MPW all declared last week but are not being returned in the IEX request.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/gpc/dividends/1m

**What time did the problem occur (including timezone)?**
Starting Nov 18, 2019

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by McQgit** [comment]
@CraigerBrau I was told recently by IEX that `/dividends` is only for historical dividends based on their exDate.  That is why recent announcements won't appear.  That endpoint was showing future exDate's until recently - but that was a bug.

I use `/upcoming-dividends` for announcements with ex-div dates in the future.  Note it's a bulk request so has a relatively expensive message weight.

I have seen their new `/time-series/advanced_dividends` and that might have what you need.  I haven't used it myself so I'm just going by their docs:
[]https://iexcloud.io/docs/api/#dividends
That's relatively expensive message weight too - at least compared to /dividends

**Comment by CraigerBrau** [comment]
@McQgit Thanks for the reply.  It would be nice for IEX to get tidbits like that in the API doc (historical only, filtered on exDate).

I was poking around `/upcoming-dividends` and it does look like the answer I needed.  I didn't know that request existed until today.  I would call it using the `symbol` instead of by `market`, so the message weight is fine.

Two caveats:
-   You have to be careful with *scheduled* yet undeclared dividends (ETFs like `SPAB`).  The response for that has "" for the amount.  I'm not a fan of this approach.  Until a value has been released, it hasn't really been declared.  Maybe another API doc opportunity.
-   Not all upcoming dividends are returned.  `ARCC` has a regular dividend and a special dividend going ex-div on 12/13.  Only the regular dividend is returned.  **This seems to be a bug.**

**Comment by McQgit** [comment]
@CraigerBrau Yes, the data is a bit, um, unpolished.

I agree about the scheduled dividends and reported it earlier here:
[]https://github.com/iexg/IEX-API/issues/1288

And, I've emailed them about missing future dividends.  They seem to show only one.  In some cases there are two with the exact dates but varying amounts yet only one is shown.  In other cases, there are two announced with different future ex-div dates yet only one is shown.  Wouldn't hurt if you also complained.

Another subtle item is that you may see incomplete data which is later completed.  This was explained as expected and how it arrives from their feed (yet not documented).  For example, when I look at all /upcoming in a morning some may not have the 'frequency' flag.  Yet, the next day (or day after that) they will.  I currently monitor for frequency, amount, and currency being missing initially although I'm not sure whether amount or currency resolve as rapidly.  I only recently detected and mitigated this issue so am only certain about frequency.  Note some seem to never have a frequency, which I later manually adjust.  These so far have been 'special' just missing the proper frequency code.  It's just initially you can't tell whether frequency is missing because it's special or because it's temporarily incomplete so I need to wait a bit.

I hope this was cogent.

**Comment by WillTron** [comment]
I was just about to post this as a bug also, as I noticed that ABBV didn't have the latest upcoming February declared dividend in the /dividends/ endpoint. I wasn't aware that future dividends are no longer included with the /dividends/ endpoint. I spent the last month and a half building a web app that uses the /dividends/ endpoint to get the past, present and future dividends across a date range of 1 year -- that's how it was working for many months. Now IEX decides it was a bug all along and only mentions it to @McQgit because he inquired about it. you're right @CraigerBrau, the documentation for the various endpoints is sometimes out of date or flat out has omissions. Couple that with IEX's decision to sometimes change the endpoint output data whenever they want without informing users in advance makes it hard to have any confidence in what you are developing will even work properly for any length of time.

**Comment by evancarter-iex** [comment]
@CraigerBrau those should be available via /dividends/next . I'll look into why KSS and ARCC (special dividend) isnt available.  

Also per your note about empty dividend amounts, some people care about knowing the date as soon as possible, so we provide that where we can, even before the amount comes into place.

@WillTron dividends/next should contain the next dividends including ABBV that hasnt changed.

**Comment by evancarter-iex** [comment]
Also a general note, support@iexcloud.io will get you faster responses for individual bugs.

**Comment by WillTron** [comment]
okay @evancarter-iex thanks, but just to be clear, I would still need to make two separate API calls in order to get past, present and future(declared) dividends whereas before it was just a single call using the /dividends/ endpoint. Before, I made a single batch API call for 50 tickers on the /dividends/ endpoint with a range of 1 year. The returned json gave me past, present and future(declared) divi's for each ticker. Now (if I'm understanding correctly) in order to get the equivalent, I need to do a separate batch call "&types=dividends&range=1y" to get past/present divi's for the date range specified and then another batch call to get future(declared) divi's using "&types=upcoming-dividends" OR "&types=dividends&range=next". Which, as a result, is a 100% increase in data weight compared to how it used to be. Is that correct? Not trying to be anal, just trying to understand how  the functionality is currently working so as to provide me with what I need.

**Comment by CraigerBrau** [comment]
@evancarter-iex Thanks for looking into why all future dividends are not being returned.  That is very problematic.

I appreciate that some might want to know when dividends are *scheduled* to be declared.  At best, though, it's an *upcoming declaration*...not an upcoming dividend.  Reporting them as an upcoming dividend is inaccurate and a waste of my data usage since I discard anything with an empty amount.

Piggy-backing on #1288, an enhancement to separate *scheduled* from the *upcoming* would be very helpful.

**Comment by McQgit** [comment]
@WillTron I'll avoid commenting on your questions to IEX regarding the API changes.

But, you'll find the message weight will be the same as you are charged for each dividend returned (not each api call).  You can confirm this by logging into your IEX Cloud account and viewing the Message Use section.  It's updated in real-time by endpoint.  Given the holiday, I thought you might appreciate at least that much.

**Comment by WillTron** [comment]
thanks for taking the time to respond @McQgit but I'm still a little confused. The only recent way I have found to get 1 year of dividends plus any upcoming(declared) dividends in a single batch call is to construct an api url that contains "&types=dividends,upcoming-dividends&range=1y&". That's a single api call, but using two different endpoints. It's my understanding that a separate data weight applies to each endpoint even if you're using the same tickers -- the Message Use section in my account shows I was dinged for both endpoints when I ran the above call. trying something like the following using a single endpoint doesn't work "&types=dividends&range=1y,next&" OR "&types=dividends&range=1y&range=next&". I'm not an API interface guru by any stretch of the imagination, so is there something I'm misunderstanding?

**Comment by McQgit** [comment]
@WillTron I tried your `&types=dividends,upcoming-dividends&range=1y` for KMB. 

I see 4 dividends in the dividends response section and 1 dividend in upcoming-dividends section.  In the Message Use on my account - the dividend endpoint increased by 4 'API Calls' and 40 'Messages used' (4x10 weight). The upcoming-dividends endpoint increased by 1 'api call' and 10 messages used (1x10 weight).

The 'api call' heading is a misnomer for dividends as you are charged 10 for each dividend item returned.  And, it is this dividend 'row' count that shows under 'API Calls'.  But, that is just informational - the 'Messages Used' column is ultimately what you pay for in IEX.

As for messages used, it wouldn't matter if you made the request in one url or more than one.  As long as 5 dividends were returned, you'd be charged 50 messages.  If one url request did not return any dividends, it would not cost anything.  For example, doing your request without the upcoming-dividends and changing the range to '1m' for KMB you will not get any data returned.  And, your message use will remain the same.

Example Detail:
```
{
  "KMB": {
    "dividends": [
      {
        "exDate": "2019-09-05",
        "paymentDate": "2019-10-02",
        "recordDate": "2019-09-06",
        "declaredDate": "2019-08-01",
        "amount": "1.03",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2019-11-28"
      },
      {
        "exDate": "2019-06-06",
        "paymentDate": "2019-07-02",
        "recordDate": "2019-06-07",
        "declaredDate": "2019-05-02",
        "amount": "1.03",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2019-11-28"
      },
      {
        "exDate": "2019-03-07",
        "paymentDate": "2019-04-02",
        "recordDate": "2019-03-08",
        "declaredDate": "2019-01-23",
        "amount": "1.03",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2019-11-28"
      },
      {
        "exDate": "2018-12-06",
        "paymentDate": "2019-01-03",
        "recordDate": "2018-12-07",
        "declaredDate": "2018-11-15",
        "amount": "1",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2019-11-28"
      }
    ],
    "upcoming-dividends": [
      {
        "exDate": "2019-12-05",
        "paymentDate": "2020-01-03",
        "recordDate": "2019-12-06",
        "declaredDate": "2019-11-21",
        "amount": "1.03",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "KMB"
      }
    ]
  }
}


```

**Comment by WillTron** [comment]
okay, thanks @McQgit for the simple to follow explanation . I clearly misunderstood data weight and how it's tabulated for dividends. Your statement "... you are charged 10 for each dividend item returned" made two things clear -- I wasn't aware that returned "empty" json element arrays for /upcoming-dividends/ are not charged against message weight and I also wasn't aware that a 1 year date range for a single ticker that has a dividend payment frequency of "monthly" (like a REIT) for example, will have a message weight of 120 (12 mo X 10 weight) -- I thought it was just a weight of 10 for the date range requested per ticker. Since I was doing a bunch of batch calls, I didn't really go through and precisely tally my "messages used" for the batch API call -- I only noticed that the tally was higher than what I was expecting. Thanks for taking the time to help me understand.

**Comment by CraigerBrau** [comment]
@evancarter-iex Since MSM is exhibiting the same behavior of not reporting all upcoming dividends (both `msm/dividends/next` and `msm/upcoming-dividends`), I sent an email to Support.
