### ISSUE TITLE
Special dividends

### ISSUE THREAD

**Issue by CraigerBrau** [iexg/IEX-API#1333]
I've seen some other posts that indicate how to identify *special dividends* when using the `/dividends` path.  It appears as of Oct 24, those identification techniques are no longer valid.

How does IEX recommend distinguishing between regular dividends and special dividends?

**Comment by McQgit** [comment]
@CraigerBrau While you wait for docs or response from IEX, I've recently been using this method:

[]https://cloud.iexapis.com/v1/time-series/advanced_dividends/(symbol)?last=1&subattribute=marker|Special&token=X

It's expensive at 75,000 message weight each dividend returned which is why I use last=1 for just the most recent.  It will return nothing, and cost nothing, if the symbol has no specials.

You can further limit this using dateField although they are currently looking at a bug report I emailed where using that in combination with above will time-out.  The above is still useful to me in some cases.

**Comment by CraigerBrau** [comment]
@McQgit I received this response from support today.

> If the 'frequency' field in the returned array is not a time period (quarterly/monthly/yearly/semi-annually), then it is a special dividend - the 'frequency' field for a special dividend could contain null or 'unspecified', for example.

Again, this is when using the `/dividends` path.

**Comment by McQgit** [comment]
@CraigerBrau   Thanks.  I've seen it 'null' as you describe but it's helpful to know that's what is intended.  

As an aside, in the /upcoming endpoint, it is not unusual to see frequency be null when a dividend first appears then change to something else a day or two later.  And, more rarely, it never changes from null and I've noticed those have been special.  I have seen 'unspecified' for confirmed specials in /upcoming so that value likely actually appears in /dividends as well.

A second aside, support just informed me the bug regarding dateField in time-series has been fixed - and it appears so to me too.

Thanks again for following through.

**Comment by WillTron** [comment]
also, as point of observation to what @CraigerBrau posted a week ago from IEX support, the returned json "frequency" key:values for company Annual and Semi-Annual distributions are NOT "yearly" and "semi-annually" -- they are "annual" and "semi-annual". Just an FYI in case there is any confusion regarding the syntax when reading the response from IEX support above

````
{
  "CTAS": {
    "dividends": [
      {
        "exDate": "2019-11-07",
        "paymentDate": "2019-12-06",
        "recordDate": "2019-11-08",
        "declaredDate": "2019-10-29",
        "amount": "2.55",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "annual",
        "date": "2019-12-18"
      }
    ]
  },
  "DIS": {
    "dividends": [
      {
        "exDate": "2019-12-13",
        "paymentDate": "2020-01-16",
        "recordDate": "2019-12-16",
        "declaredDate": "2019-12-04",
        "amount": "0.88",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "semi-annual",
        "date": "2019-12-18"
      },
      {
        "exDate": "2019-07-05",
        "paymentDate": "2019-07-25",
        "recordDate": "2019-07-08",
        "declaredDate": "2019-06-26",
        "amount": "0.88",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "semi-annual",
        "date": "2019-12-18"
      }
    ]
  }
}
````
