### ISSUE TITLE
[Issue] - Calling batch returns different values with symbols with + sign

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#1352]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
When calling the company API with the batch command on a symbol that has a + sign, the + sign is being removed. This does not happen when the batch command is not used

**What time did the problem occur? (with timezone)**
3:30AM EST

**What is the expected behavior?**
Not sure which is correct

**Your environment (e.g. browser, OS, API version, language):**
Chrome Win10

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/PIC+/company?token=
https://cloud.iexapis.com/stable/stock/market/batch?types=company&token=pk_&symbols=PIC+

**What are the steps to reproduce the bug?**
Run API

**Additional context**

```
https://cloud.iexapis.com/stable/stock/PIC+/company?token=
{"symbol":"PIC+","companyName":"Pivotal Investment Corp. II",
```

```
https://cloud.iexapis.com/stable/stock/market/batch?types=company&token=pk_&symbols=PIC+
{"PIC":{"company":{"symbol":"PIC","companyName":"Pivotal Investment Corp. II",
```

**Comment by McQgit** [comment]
@jesseorosz Good one :)  That's a peculiar character in URL formatting - not unique to IEX.  They'll have to comment whether they plan to accommodate that.  In the meantime, if you encode any plus sign in the symbol as follows it will work (using %2B instead of +):

https://cloud.iexapis.com/v1/stock/market/batch?symbols=PIC%2B&types=quote&token=X

Plus signs in the base of the url are not similarly affected - as you've discovered.  For the history, see
[]https://en.wikipedia.org/wiki/Query_string

Searching stackoverflow or google for `url encoding of plus sign` will provide lots of hits.

**Comment by jesseorosz** [comment]
@McQgit nice! appreciate the reply

**Comment by evancarter-iex** [comment]
The Query String wiki article talks about it a lot. URL encoding is safer most of the time in general so use that with any part of the query string. Closing.
