### ISSUE TITLE
OHLC empty result set

### ISSUE THREAD

**Issue by rmantovani** [iexg/IEX-API#1367]
##  Welcome to IEX Cloud's Github Community.  To receive the fastest response from IEX Cloud, please reach out to IEX Cloud's Support team directly at support@iexcloud.io. 

**Clearly describe the problem**
Ohlc is empty

**What time did the problem occur? (with timezone)**
20:22 GMT+3

**What is the expected behavior?**
get last data

**Your environment (e.g. browser, OS, API version, language):**
Linux

**API URL (if applicable)**
https://cloud.iexapis.com/stable/stock/aapl/ohlc?token=xxxxxxx

**What are the steps to reproduce the bug?**
use api above

**Additional context**

**Comment by McQgit** [comment]
@rmantovani  I think that's a Nasdaq UTP issue.  Had you tried a stock listed on a different exchange (like NYSE) it should have been ok.  IEX explains the issue here:
https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud

It is also mentioned in the Notes section in their docs for ohlc endpoint.

It looks to me like after 8p eastern the ohlc is filled in - even for Nasdaq listed securities (like AAPL).
