### ISSUE TITLE
Pagination or record per call

### ISSUE THREAD

**Issue by ankitkatmore** [iexg/IEX-API#1386]
Do we have any pagination and records per page from API call. Please let me know ASAP.

**Comment by McQgit** [comment]
@ankitkatmore  I might volunteer some help.  Can you provide a specific example of what you want from a particular endpoint or api?

**Comment by ankitkatmore** [comment]
I am fetching the symbol from some exchange on daily basis and that send 2000 records so i need to paginate them and need to save in database. please let me know if have any qiestions

**Comment by McQgit** [comment]
@ankitkatmore Sorry.  Can't help with such limited info.  Need at least a sample url

**Comment by ankitkatmore** [comment]
This is URL, can i use pagination or records per page. 
https://cloud.iexapis.com/stable/ref-data/exchange/TSX/symbols?token=

**Comment by McQgit** [comment]
@ankitkatmore I don't know of any paging method for that.  However, I have some suggestions:

You could use the `filter `query to reduce which fields are returned.  This will reduce the number of bytes transferred - if that's a concern.
https://iexcloud.io/docs/api/#filter-results

I did that url request and don't think the response is very large - only about 50KB.  And, was very fast.  But, you could consider running this less frequently - like once a week.  I can't imagine the symbol list of that exchange will change very often.  I do something similar for US and update my own database twice / week rather than daily.

You haven't explained why you needed to paginate so this was the best I could do.  Good luck.

**Comment by ankitkatmore** [comment]
I am calling multiple APIs, can you please let me know.

**Comment by McQgit** [comment]
@McQgit Yeah, sorry, I don't know how to help you further with the info you have provided.
