### ISSUE TITLE
Upcoming Dividends broken?

### ISSUE THREAD

**Issue by cgailey** [iexg/IEX-API#1392]
The last few days the upcoming-dividends endpoint doesn't seem to be showing announced dividends.  A few examples below for dividends announced Jan 23, but not showing in 'upcoming-dividends':

'PKI', 'COST', 'ETFC', 'JBL', 'KBH', 'VLO'

Using URL: https://cloud.iexapis.com/v1/stock/vlo/upcoming-dividends?token=

Thanks,
.cg.

**Comment by joshuablackburn-iex** [comment]
The upcoming dividends endpoint is based on ex date rather than announce date. If you take a look at the time series endpoint documentation, you can use the calendar parameter as well as the date parameter to query for dividends by announce date.

**Comment by McQgit** [comment]
@joshuablackburn-iex  Please look at this again.  There is a clear problem - even with time-series.

Adding on to @cgailey, KMB on Jan23 announced a dividend with dates: Record=2020-03-06, and Pay=2020-04-02 (making the ExDiv 2020-03-05).  Yet, this dividend does not appear at:
https://cloud.iexapis.com/v1/stock/kmb/upcoming-dividends?token=X
or
https://cloud.iexapis.com/v1/stock/market/upcoming-dividends?token=X

This is the same pattern as those already mentioned by cgailey.  Until recently, a dividend like this would have appeared in /upcoming the day after it was announced, but, starting about a week ago (Jan16/17), all new announcements quit showing up at these endpoints.  It is as if you have not gotten any new data from your provider since then.

Further, given your suggestion to use time-series, I tried that endpoint but the most recent dividend is the one announced last Nov and paid on Jan3.  It doesn't have the latest one announced Jan23:
https://cloud.iexapis.com/v1/time-series/advanced_dividends/kmb?last=1&token=X

Other background:
KMB's press release.  
https://kimberlyclark.gcs-web.com/news-releases/news-release-details/kimberly-clark-announces-year-end-2019-results-and-2020-outlook

**Comment by CraigerBrau** [comment]
@joshuablackburn-iex Yes, something is amiss.  I did not get any announced dividends this week when I expected some.  Another example is SJM using https://cloud.iexapis.com/stable/stock/sjm/dividends/next request.

https://investors.jmsmucker.com/2020-01-17-The-J-M-Smucker-Company-Declares-Dividend

**Comment by joshuablackburn-iex** [comment]
We are investigating with the provider.

**Comment by WillTron** [comment]
This is possibly an unrelated issue from the OP's since it's been a missing dividend value for several weeks and is potentially a recurring issue, but ENB is another ticker regarding /upcoming-dividends EP that is missing a dividend "amount" value. Related: ENB had a missing div value for quarter 4Q2019. In that case, the /dividend EP was missing the latest USD div amount value but included the CAD amount value (reference post #1320)

```
{
  "ENB": {
    "upcoming-dividends": [
      {
        "exDate": "2020-02-13",
        "paymentDate": "2020-03-01",
        "recordDate": "2020-02-14",
        "declaredDate": "2019-12-10",
        "amount": "",
        "flag": "Cash",
        "currency": "USD",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "symbol": "ENB"
      }
    ]
  }
}
```

**Comment by McQgit** [comment]
@WillTron  Yeah, that's a different problem.  Sometimes foreign / ADR stocks are missing their amount but are otherwise in /upcoming.  I saw that w/ENB as well and it has persisted for more than 30 days.  Better to start a new thread for that.  This thread involves many stocks (perhaps all) being missing from /upcoming entirely.

**Comment by cgailey** [comment]
I am seeing dividends on this endpoint again.  Thanks!

**Comment by McQgit** [comment]
@cgailey You beat me by seconds.  The about 2000 symbols I track dividends for are now correct - even picking up the missed ones since Jan16/17.
