### ISSUE TITLE
Unexpected (?) value returned for changePercent

### ISSUE THREAD

**Issue by giro83** [iexg/IEX-API#148]
## Summary

$ curl -s -f https://api.iextrading.com/1.0/stock/ffiv/quote | jq .changePercent
8e-05
$ date
Sun 24 Dec 09:54:47 GMT 2017

Is the API meant to return that value (8e-05)? Or is it experiencing an issue with that stock?

If that's the expected value, is that meant to be scientific notation?

As in +0.00008%?

A similar stock that also had a +0.01 change (MSFT) returns changePercent using decimal notation:

$ curl -s -f https://api.iextrading.com/1.0/stock/msft/quote | jq -r .changePercent
0.00012
$ date
Sun 24 Dec 10:11:04 GMT 2017

Maybe you switch between decimal / scientific notations after a certain value? I didn't see a reference to this in your documentation. If that's the case, it would be worth mentioning.

An option to enable/disable this would also be nice, or special handling may be needed in the client-side code of your users.

**Comment by giro83** [comment]
?displayPercent=true is perhaps related to the question...

**Comment by jcape** [comment]
@giro83 Using displayPercent means to pre-format the numbers as actual percentages (i.e. if you wanted to display the value), whereas the lack of displayPercent means give the percentage as a raw decimal:

```
?displayPercent=true: 0.8
(nothing):            0.008
```

The price of FFIV is 132.20, so 132.20 * 0.00008 = 0.010576---that is, one penny, with a floating point calculation error. The minimum tick size (price increment) of a FFIV is one penny so that all checks out as a valid value.

In terms of scientific notation itself, it is a valid numeric representation in the JSON format, and the standard does not add any further requirements around it, so the best guidance I can offer is to select a parser that is robust enough to handle scientific notation in any, all, or no cases, as JSON may contain scientific notation in any place there is a numeric value.
