### ISSUE TITLE
latestVolume and volume are NULL when getting gainers

### ISSUE THREAD

**Issue by samboustani** [iexg/IEX-API#1522]
When retrieving the GAINERS list there are often times NULL values in some of the fields, in this case, especially latestVolume and volume fields.  previousVolume and avgTotalVolume have values.  This is random.

DATA URL: https://cloud.iexapis.com/stable/stock/market/list/gainers?listLimit=20&format=json

TIME: 14:00 PM CST

**What is the expected behavior?**
Return values for fields that should have some intraday.

**What are the steps to reproduce**
go to DATA URL: https://cloud.iexapis.com/stable/stock/market/list/gainers?listLimit=20&format=json and view results

**Your environment (e.g. browser, OS, API version, language):**
Google Chrome browser, API client in C#

**Comment by voyager-gold** [comment]
Same here
api endpoint is quote.
It returns null for volume and latest volume.

**Comment by voyager-gold** [comment]
@samboustani Can you please tell me how you sorted it out?

**Comment by joshuablackburn-iex** [comment]
From our documentation:

IEX Cloud provides real time prices, volume, and quotes for all NMS US securities; sourced from the Investors Exchange. In order to receive 15 minute DELAYED Nasdaq-listed security data through this endpoint Nasdaq UTP requires you to complete a Vendor Agreement. Delayed prices include open, close, extended hours prices, and other derived values. All users will continue to receive real time Investors Exchange data for free. 15 minute DELAYED NYSE listed symbols are only available to paid users due to reporting requirements.
