### ISSUE TITLE
null values in Quote

### ISSUE THREAD

**Issue by Suukkan** [iexg/IEX-API#1541]
Hi Friends,
I am trying to Use Quote endpoint and i notice that several important parameters are NULL. I tried the URL and PyEX (python library). I had the same result. I am a new user and joined today. below is the result i get, can u let me know if this is issue with my account or the way i handle this.

**URL i tried:** https://cloud.iexapis.com/stable/stock/AAPL/quote?token=XXXXXXXX

{"symbol":"HLT","companyName":"Hilton Worldwide Holdings, Inc.","primaryExchange":"New York Stock Exchange","calculationPrice":"tops","open":null,"openTime":null,"openSource":"official","close":null,"closeTime":null,"closeSource":"official","high":null,"highTime":1595873663354,"highSource":"15 minute delayed price","low":null,"lowTime":1595856883156,"lowSource":"15 minute delayed price","latestPrice":76.97,"latestSource":"IEX real time price","latestTime":"2:29:28 PM","latestUpdate":1595874568032,"latestVolume":null,"iexRealtimePrice":76.97,"iexRealtimeSize":26,"iexLastUpdated":1595874568032,"delayedPrice":null,"delayedPriceTime":null,"oddLotDelayedPrice":null,"oddLotDelayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":77.43,"previousVolume":1257384,"change":-0.46,"changePercent":-0.00594,"volume":null,"iexMarketPercent":0.05087086399128943,"iexVolume":79052,"avgTotalVolume":3290561,"iexBidPrice":62,"iexBidSize":200,"iexAskPrice":100,"iexAskSize":400,"iexOpen":null,"iexOpenTime":null,"iexClose":76.97,"iexCloseTime":1595874568032,"marketCap":21340779170,"peRatio":29.66,"week52High":115.48,"week52Low":44.3,"ytdChange":-0.311189,"lastTradeTime":1595874568032,"isUSMarketOpen":true}

**Comment by christiankm** [comment]
It seems to be quite sporadic. I have the same "issue".
Sometimes values are null and you should account for this in your app/code.

I think it happens if the data is not available for that item, or depending on date/time.

**Comment by unozerocode** [comment]
We are seeing the same issue. We very carefully created validations directly from the documentation for [Quote](https://iexcloud.io/docs/api/#quote). Wherever the document says a null is possible, we allow nulls, otherwise we marked it as required. A call to the API at endpoint _https://sandbox.iexapis.com/stable/stock/IBM/quote_ for stock symbol "IBM" gave us the following validation errors:

     -  openTime: {"can't be blank", [validation: :required]},
     -  close: {"can't be blank", [validation: :required]},
     -  closeTime: {"can't be blank", [validation: :required]},
     -  latestVolume: {"can't be blank", [validation: :required]},
     -  iexRealTimePrice: {"can't be blank", [validation: :required]},
     -  iexRealTimeSize: {"can't be blank", [validation: :required]},
     -  iexLastUpdated: {"can't be blank", [validation: :required]},
     -  delayedPrice: {"can't be blank", [validation: :required]},
     -  delayedPriceTime: {"can't be blank", [validation: :required]},
     -  oddLotDelayedPrice: {"can't be blank", [validation: :required]},
     -  oddLotDelayedPriceTime: {"can't be blank", [validation: :required]},
     -  extendedPrice: {"can't be blank", [validation: :required]},
     -  extendedChange: {"can't be blank", [validation: :required]},
     -  extendedChangePercent: {"can't be blank", [validation: :required]},
     -  extendedPriceTime: {"can't be blank", [validation: :required]},
     -  volume: {"can't be blank", [validation: :required]},
     -  iexMarketPercent: {"can't be blank", [validation: :required]},
     -  iexvolume: {"can't be blank", [validation: :required]},
     -  iexBidPrice: {"can't be blank", [validation: :required]},
     -  iexBidSize: {"can't be blank", [validation: :required]},
     -  iexAskPrice: {"can't be blank", [validation: :required]},
     -  iexAskSize: {"can't be blank", [validation: :required]},
     -  iexOpen: {"can't be blank", [validation: :required]},
     -  iexOpenTime: {"can't be blank", [validation: :required]},

And if we take a look at the actual response from the API we can see that indeed those values are null:

`{
   "symbol":"IBM",
   "companyName":"International Business Machines Corp.",
   "primaryExchange":"k SoY xcctganeNEwkor eh",
   "calculationPrice":"close",
   "open":null,
   "openTime":null,
   "openSource":"flaiocif",
   "close":null,
   "closeTime":null,
   "closeSource":"foifcail",
   "high":null,
   "highTime":1647649879539,
   "highSource":"ermyneeicd1taeplu 5  id",
   "low":null,
   "lowTime":1629134897493,
   "lowSource":"dniere lie1mp u5atec yd",
   "latestPrice":127.2,
   "latestSource":"Close",
   "latestTime":"September 4, 2020",
   "latestUpdate":1667687086644,
   "latestVolume":null,
   "iexRealtimePrice":null,
   "iexRealtimeSize":null,
   "iexLastUpdated":null,
   "delayedPrice":null,
   "delayedPriceTime":null,
   "oddLotDelayedPrice":null,
   "oddLotDelayedPriceTime":null,
   "extendedPrice":null,
   "extendedChange":null,
   "extendedChangePercent":null,
   "extendedPriceTime":null,
   "previousClose":124.76,
   "previousVolume":5752785,
   "change":-2.22,
   "changePercent":-0.01809,
   "volume":null,
   "iexMarketPercent":null,
   "iexVolume":null,
   "avgTotalVolume":3908200,
   "iexBidPrice":null,
   "iexBidSize":null,
   "iexAskPrice":null,
   "iexAskSize":null,
   "iexOpen":null,
   "iexOpenTime":null,
   "iexClose":126.325,
   "iexCloseTime":1615224235126,
   "marketCap":114026194757,
   "peRatio":13.83,
   "week52High":158.81,
   "week52Low":92.1,
   "ytdChange":-0.119002,
   "lastTradeTime":1627519025665,
   "isUSMarketOpen":false
}`

The issue here is that if the documentation does not specify all "legal" values that the platform can return, it is impossible for us to code a reliable solution that will call this API. The documentation either needs to be corrected or some sort of blanket statement needs to be displayed above each endpoint to the effect that there is no spec, the data values we get back may or may not be null depending on unknown factors.
For us to have to poke holes in our validation logic to permit nulls for so many fields will make the business logic hopelessly complex, the correct solution is to properly document the API so that those who implement according to spec will not receive unexpected values, and also the platform should simply not be returning nulls for data that should be perfectly available.
If this has something to do with the fact that we are using the sandbox, then it is still a problem because the documentation says data can be random, which is fine, but if it can be null when a production call would have a value, then the code we write during this phase will have to be gone over again with the different validation logic used in production. 
Are we missing something basic here?

**Comment by timpaine-iex** [comment]
@unozerocode do you see this for non-nasdaq stocks? 
https://intercom.help/iexcloud/en/articles/3210401-how-do-i-get-nasdaq-listed-stock-data-utp-data-on-iex-cloud

**Comment by timpaine-iex** [comment]
<img width="727" alt="Screen Shot 2020-12-16 at 10 14 22 AM" src="https://user-images.githubusercontent.com/74613173/102367206-7de18a80-3f87-11eb-8718-7bd1727ee269.png">

**Comment by unozerocode** [comment]
Not sure, we moved on to other projects and are not using iex anymore, but probably the API should return an error like "Requires UTP authorization" so that us developers can know what to fix, instead of dealing with garbage data. Seriously you guys need to get somebody that knows how to design API´s.

**Comment by timpaine-iex** [comment]
@unozerocode no worries, in the future I recommend reading the documentation of the APIs you use.

**Comment by timpaine-iex** [comment]
@Suukkan closing as "can't repro", please give me a ping if you're still seeing issues and we can reopen

**Comment by mindaugasw** [comment]
Hello, I have the same issue with `volume` and `latestVolume` fields being null in Quote endpoint. However, in the [article about UTP data](https://iexcloud.zendesk.com/hc/en-us/articles/1500012484401-How-do-I-get-Nasdaq-listed-stock-data-UTP-Data-on-IEX-Cloud-) nothing is mentioned about volume.
So is this because I don't have UTP authorization or some other issue?

However, this is an issue only during trading hours. When market is closed, `volume` and `latestVolume` fields return correct data.

Example request:
`https://cloud.iexapis.com/v1/stock/AAPL/quote?token=`
Response when market is open:
```json
{
    "latestVolume": null,
    "volume": null,
    ...
}
```
Response when market is closed:
```json
{
    "latestVolume": 98670687,
    "volume": 98670687,
    ...
}
```
