### ISSUE TITLE
SSE Streaming for insider-transactions

### ISSUE THREAD

**Issue by a269ch** [iexg/IEX-API#1548]
How use with SSE Streaming for insider-transactions (https://iexcloud.io/docs/api/#insider-transactions) ? 
I need to receive insider-transaction update for 470+ stocks.  I need to receive this through SSE or I have to do 470+ get-requests in a few minutes.  Tell me how to implement this task, so as not to high load your service with requests and not to
 compare constantly received data every few minutes?

**Comment by joshuablackburn-iex** [comment]
Batch requests allow you to query up to 100 symbols in one API call.

**Comment by a269ch** [comment]
This is not the most convenient way. A lot of data has to be saved. I hope you add SSE Streaming or WebSokets or WebHook.

**Comment by timpaine-iex** [comment]
feel free to submit/upvote here: https://iexcloud.io/console/roadmap

`batch` is 5 requests for this data, SSE is designed for live updates so I don't think it would be more convenient. In a hypothetical implementation, you'd receive an update per transaction per ticker, so rather than 5 api calls you'd end up getting thousands of individual SSE updates.
