### ISSUE TITLE
Quote endpoint - latestTime off by one day

### ISSUE THREAD

**Issue by gstoa** [iexg/IEX-API#158]
## Summary
Using the Quote endpoint, the latestTime value appears to be one day off, or I may not understand what the field is intended to represent.

## Details
The last trading day was Friday, 20117-12-29.  After calling the Quote endpoint on Sunday, 2017-12-31, the JSON returned from [(https://api.iextrading.com/1.0/stock/aapl/quote)] shows the following value for latestTime.

latestTime: "December 28, 2017"

### Date/time of issue
2017-12-31 09:34 (Pacific)

### API URL
[https://api.iextrading.com/1.0/stock/aapl/quote]

### What you expected to happen
latestTime: "December 29, 2017"

### What actually happened
```
{
symbol: "AAPL",
companyName: "Apple Inc.",
primaryExchange: "Nasdaq Global Select",
sector: "Technology",
calculationPrice: "close",
open: 171,
openTime: 1514471400132,
close: 169.23,
closeTime: 1514494800281,
high: 170.59,
low: 169.22,
latestPrice: 169.23,
latestSource: "Close",
latestTime: "December 28, 2017",
latestUpdate: 1514494800281,
latestVolume: 25926128,
iexRealtimePrice: null,
iexRealtimeSize: null,
iexLastUpdated: null,
delayedPrice: 169.14,
delayedPriceTime: 1514584798552,
previousClose: 171.08,
change: -1.85,
changePercent: -0.01081,
iexMarketPercent: null,
iexVolume: null,
avgTotalVolume: 26773367,
iexBidPrice: null,
iexBidSize: null,
iexAskPrice: null,
iexAskSize: null,
marketCap: 860882486880,
peRatio: 19.23,
week52High: 177.2,
week52Low: 114.76,
ytdChange: 0.45699526474386554
}
```

**Comment by evancarter-iex** [comment]
Is this still a problem?

**Comment by McQaws** [comment]
I had the same problem after the Fri 12/29 close and through the weekend as @gstoa 

In my case all 50 tickers or so that I checked were wrong in the same way as described here.  The dates are now correct.  I'll further add that not only was the LatestTime wrong, all the related unix time stamps were also wrong by 24 hours.  You can see that in the OP - just convert the unix times and they'll be Dec 28 - not Dec 29.

While it's not a problem for current quotes, is there any assurance this won't happen at year-end in 2018?  I was just starting to assess your api and seeing end-of-year close quotes apparently "stale" was not a good omen.

**Comment by evancarter-iex** [comment]
This is most likely related to our [issue on friday](https://twitter.com/IEXstatus/status/946869559566524416). It should not be an issue going forward.
