### ISSUE TITLE
[Data] Incorrect Price to Book for Google.

### ISSUE THREAD

**Issue by whitewolf92** [iexg/IEX-API#1611]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
IEXdata is showing P/B ratio of 1.87 for GOOG which is suspiciously too low or wrong. Yahoo or other vendors' data show GOOG P/B within a range of 4.7 to 5.5.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/goog/advanced-stats

**What time did the problem occur (including timezone)?**
GMT +8 5pm

**What is the expected behavior?**
Well, it shows GOOG P/B ratio to be too cheap! I check with yahoo finance and many external sources and their ranges is from 4.5 onwards.

**What are the steps to reproduce**
Call the advanced-stats api.

**Your environment (e.g. browser, OS, API version, language):**
Chrome

**Additional context**

**Comment by timpaine-iex** [comment]
Thanks for reporting, I'm seeing a pb of `5.49` for `GOOGL` as of 21 Dec so this was likely resolved, either via the Dec 1 data migration or due to some weirdness with the different share classes. In either case, if you use the A shares you should now see the correct number from the `advanced-stats` endpoint.
