### ISSUE TITLE
400 Bad request with axios

### ISSUE THREAD

**Issue by JJunTing** [iexg/IEX-API#1615]
I'm trying to call a stock quote API with my token, and it's pretty normal when I use my browser and Postman to send a get request, but when I send a get request with Axios, it keep telling me it's a 400 bad request. I don't know how to fix it.

I get stuck at this point for hours, please help me. Thank you!

<img width="645" alt="螢幕截圖 2020-11-26 15 20 48" src="https://user-images.githubusercontent.com/70137139/100333369-7cb6e080-300d-11eb-9c70-31713e0c3b62.png">
<img width="383" alt="螢幕截圖 2020-11-26 15 21 16" src="https://user-images.githubusercontent.com/70137139/100333409-87717580-300d-11eb-8efc-0a9e3c331b27.png">
<img width="510" alt="螢幕截圖 2020-11-26 15 23 09" src="https://user-images.githubusercontent.com/70137139/100333426-8b04fc80-300d-11eb-8055-0c53698333f9.png">

**Comment by olivertilk** [comment]
Axios is working fine for me. My code is:
const XLPdata1W = await axios.get('https://sandbox.iexapis.com/stable/stock/XLP/chart/1m?token=Tpk_8..........);

One possibility is your use of baseUrl. It's possible your call goes to 'https://sandbox.iexapis.com/stable/stock/XLP/chart/1m?token=Tpk_8........../' with the extra backslash at the end because the formula is baseUrl + url so since your call is to '/' axios adds the backslash. That would definitely get you a 400 status code.
