### ISSUE TITLE
[Data] Dividend amount precision

### ISSUE THREAD

**Issue by marekk657** [iexg/IEX-API#1644]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
It seems like dividend precision is changed a lot.
For GD, previous period it reported 1.1 as dividend amount, while now API returns "amount":1.100000023841858

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/GD/dividends/next?token=token

**What time did the problem occur (including timezone)?**
First time i saw yesterday (03.12.2020) about 13.00 UTC.

**What is the expected behavior?**
Either fix precision and don't send random float or document that behavior.

**What are the steps to reproduce**
See Data URL and check amount.

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by WillTron** [comment]
Agree. When JPM issues a quarterly dividend of $0.90, it's a quarterly dividend of ninety cents -- NOT $0.8999999761581421. And there are thousands of dividends with precision issues for many tickers since the IEX data "update" on Dec 1st. When you are comparing numerical data from one data point to another and have to start relying on floats, floors, ceilings, and rounding functions to X number of significant digits, things can tend to get squirrelly fairly quickly which makes the current divi data being provided as basically WRONG.

**Comment by McQgit** [comment]
@WillTron I agree and also emailed IEX about it.  In the meantime I've had good luck 'repairing' the amount I get from them by rounding to 6 places and removing trailing zeros to the right of the decimal beyond 2 places (so I see 1.00 and 1.20 for example).  When they have '0' I replace it with null to avoid seeing 0.00 (which just looks odd to me).  By repairing what I get back I avoid having to modify every comparison as you describe (which is painfully messy - agreed).

This works well for typical equity and ETF dividends.  I saw a few bond distributions that I'm not sure rounding to 6 places is correct but I don't need those so it's academic.

Given all their other transition issues I don't think this is likely to gain high priority so I decided on this work-around.

**Comment by WillTron** [comment]
@McQgit thanks for the tips. I was already starting to experiment with similar techniques that you mentioned. Originally I was trying to address the new precision issue from within some custom functions as they were being called in my application which was leading to unpredictable results. Like you stated, tweaking the data right after the json output is returned from the api call appears to be the better way to go.

I was actually hoping IEX would see the error of their ways and fix this issue fairly quickly so that a "band-aid" approach wouldn't be necessary by any end-user. You may be right that the dividend data related EP's might be near the bottom of the list as far as priorities go. It's hard to tell what mode IEX is in anymore -- "2 steps forward and 1 step back" OR "1 step forward and 2 steps back". According to the marketing material that they have been putting out the last month+ it appears they have added many new end-points of data -- which is great, but my main use are the dividends, stats and quote EP's. So when the way data is handled changes for any of those EP's it can get frustrating to say the least -- especially when everything was working great on the user's end and the  issue at hand is arguably completely avoidable like this numerical precision issue.

**Comment by mukinabis** [comment]
> but my main use are the dividends, stats and quote EP's
Can you show your site?

> EP's
EP - end price?

**Comment by mukinabis** [comment]
@WillTron 

> but my main use are the dividends, stats and quote EP's

Can you show your site?

> EP's

EP - end price?

**Comment by WillTron** [comment]
@mukinabis sorry my bad .... just lazy I guess. In my posts I'm using EP as an acronym for "end-point". Also, my site is an internal intranet site not accessible by the general public.

**Comment by mukinabis** [comment]
> @mukinabis sorry my bad .... just lazy I guess. In my posts I'm using EP as an acronym for "end-point". Also, my site is an internal intranet site not accessible by the general public.

ok

**Comment by evancarter-iex** [comment]
Fixed.
