### ISSUE TITLE
[Issue] websockets example doesn't work with socket-io 3.0.3

### ISSUE THREAD

**Issue by rubys** [iexg/IEX-API#1646]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

Example can be found here: https://iextrading.com/developers/docs/#websockets

It works with socket-io 2.3.0, and fails (produces no output) with socket-io 3.0.3.

**What time did the problem occur? (with timezone)**

I first noticed this about a week ago, and tracked it down today.  EST, if that matters.

**What is the expected behavior?**

The example shows current value then updates of the subscribed stocks during trading hours.

**Your environment (e.g. browser, OS, API version, language):**

Node.js on Linux and MacOS.

**API URL (if applicable)**

https://ws-api.iextrading.com/1.0/tops

**What are the steps to reproduce the bug?**

Run the example from the web site.

**Additional context**

None.

**Comment by timpaine-iex** [comment]
SocketIO 3 is not backwards compatible https://socket.io/blog/socket-io-3-release/

From the [migration docs](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html): 
"TL;DR: due to several breaking changes, a v2 client will not be able to connect to a v3 server (and vice versa)"

There are no plans to upgrade to SocketIO 3 at this time, so for now use a socketIO 2 client.
