### ISSUE TITLE
[Issue] DOC: No documentation for Relevant Stocks

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1653]
##  Welcome to IEX Cloud's Github Community.  

The documentation for the ``relevant`` endpoint has been removed. It was previous located at https://iexcloud.io/docs/api/#relevant-stocks. The endpoint is still functional.

**Comment by timpaine-iex** [comment]
@addisonlynch its deprecated, I will make a note to ensure we announce prior to removing functionality but I recommend marking it (I use `deprecation` for this, e.g. [here](https://github.com/timkpaine/pyEX/blob/3efa9a9379518189ef068478bc87b214a55923ef/pyEX/markets/markets.py#L7) instead of raising an exception at the time of use)

**Comment by timpaine-iex** [comment]
https://iexcloud.io/docs/api/#relevant-stocks-deprecated
