### ISSUE TITLE
[Issue] Missing documented fields for fundamental data

### ISSUE THREAD

**Issue by addisonlynch** [iexg/IEX-API#1655]
**Clearly describe the problem**

This issue is a generalization of #1636 

Some fundamentals (balance sheet, income statement, cash flows) fields are missing. For instance Balance Sheet does not include ``totalCurrentLiabilities`` as is documented. There may be other fields missing as well.

**What time did the problem occur? (with timezone)**

2:20pm HST 12/6/20

**What is the expected behavior?**

All documented fields accounted for

**Your environment (e.g. browser, OS, API version, language):**

Sandbox, API V1

**API URL (if applicable)**

https://sandbox.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=balance-sheet&last=4&token=

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by virattt** [comment]
+1 

I get a feeling that parts of the fundamentals funnel (including balance-sheet) broke during a recent migration.  Seeing some regressions.

**Comment by addisonlynch** [comment]
Opened #1654 as well for limited periods returned for these endpoints

**Comment by virattt** [comment]
Yeah...I have reported similar/related issues over the past week or so:
- https://github.com/iexg/IEX-API/issues/1636 (longTermDebt, totalDebt, totalCash are null in /financials API )
- https://github.com/iexg/IEX-API/issues/1623 ("last" parameter wasn't working for income, balance-sheet, cash-flow)

Haven't gotten any responses from IEX, which has been really disappointing, given that I am paying for their service.

Currently researching and reaching out to other data providers 😞 🤷‍♂️ .  I really liked IEX's service, when it worked

**Comment by MorningSleeper** [comment]
> Also, moving forward, IEX is deprecating income, balance-sheet, and cash-flow (starting May 1, 2021). They are consolidating the fundamentals data into a new API (advanced-fundamentals) and charging 75,000 messages per report per ticker (which currently costs 5,000 messages).

Yikes, so if I just wanted the data from income endpoint which is currently 1000 messages, it will cost 75 times as much on May 1st 2021 ?!

**Comment by virattt** [comment]
Yes, that is my understanding.  I have been emailing support@iexcloud.io and what they have told me is: income, balance-sheet, and cash-flow will be deprecated on May 1, 2021.  To get the same data, I need to use the new Advanced Fundamentals API, which costs 75,000 per record per ticker symbol.  The reason is that they switched data providers and the new data provider is more expensive (?)

The 75,000 message cost is untenable.  Perhaps you could email them and let them know you feel similarly?

Initially, the cost of the new Advanced Fundamentals API was 750,000 messages, but then they reduced it to 75,000 messages after "internal discussions".  Still feels very heavy-handed to charge 75,000 messages for something that today costs <= 5,000 messages (eg. a record for income, balance-sheet, and cash-flow would cost around 5,000 messages today).

I am hoping the 75,000 is just a typo.

**Comment by MorningSleeper** [comment]
Ok, thanks for the additional info.

**Comment by timpaine-iex** [comment]
@addisonlynch docs have been updated and sample json should match documented response attributes for those three, can you double check. ping me if there are still mismatches and I'll reopen
