### ISSUE TITLE
Can't Get Current Day OHLCV Data

### ISSUE THREAD

**Issue by JimLynchCodes** [iexg/IEX-API#1662]
Hi, I am wondering when I should expect the current days info to show up in the "historical prices" endpoints?

For example, I get a nice response when I call this endpoint:
```
https://cloud.iexapis.com/stable/stock/goog/chart/date/20201208?chartByDay=true&token=pk_my_token
```

Today is wednesday, december 9th, 2020. It is now 10:30pm, 6 hours after the US markets have closed... but I strangely just get an empty array when switching the "8" to a "9" in the previous endpoint. 🤔

So I am wondering why this does not give me any data and how to get OHLCV data ASAP at the end of the day...

Thanks

**Comment by adamwozney-iex** [comment]
Hey @JimLynchCodes - Thanks for flagging. We recently updated our READme file and moved all support or bug related questions to another channel. Please reach out to support@iexcloud.io and our support team will follow-up with you there. Sorry for any confusion. 

Thanks.

**Comment by JimLynchCodes** [comment]
@adamwozney-iex why is that? when dealing with emails you need to repetitively answer the same question again and again rather than having a single place for all to immediately find the solution...

**Comment by timpaine-iex** [comment]
@JimLynchCodes for issues where users are able to help other users, we'll be moving to a forum to be a better environment for collaboration (See the [readme](https://github.com/iexg/IEX-API#iex-cloud-github)])

For issues where users can't really help each other (e.g. a data issue or something on our end that we need to fix), the email system gives us some tooling that helps us better track and prioritize things, so while it seems a little weird to potentially ask a bunch of people to submit the same problem, it actually is easier for us to track and manage than via GitHub (especially since on GitHub, sometimes people open duplicate issues, sometimes they just `watch` and existing issue, sometimes they 👍 an issue report, etc). 

Appreciate your patience, and thanks for reporting this issue

**Comment by McQgit** [comment]
@timpaine-iex One thing lost to us users is visibility on what is already reported.  I am then stuck having to diagnose and package a trouble report for things that may already be in the works.  It would be helpful if you would post 'known issues' somewhere so we can avoid duplication.  Just food for thought.

**Comment by timpaine-iex** [comment]
@McQgit good idea, though there is value in having different repro's as sometimes they exhibit the same manifestation of discrete underlying bugs. We'll try to keep our users' preferences in mind as we build out our community tooling, so these types of comments and ideas are very helpful.

**Comment by timpaine-iex** [comment]
according to the documentation
<img width="294" alt="Screen Shot 2020-12-21 at 12 03 30 PM" src="https://user-images.githubusercontent.com/74613173/102802385-8cafaf00-4384-11eb-8134-556876f076a6.png">

**Comment by timpaine-iex** [comment]
There are alternatives, though keep in mind that for e.g. `goog` in your example, there are certain nasdaq-specific restrictions

<img width="856" alt="Screen Shot 2020-12-21 at 12 04 03 PM" src="https://user-images.githubusercontent.com/74613173/102802438-9f29e880-4384-11eb-905b-4b9f7eb67c1e.png">

**Comment by timpaine-iex** [comment]
`quote` is also an option (and a cheap one), though keep in mind it carries many of the same restrictions 
<img width="899" alt="Screen Shot 2020-12-21 at 12 05 11 PM" src="https://user-images.githubusercontent.com/74613173/102802516-c7b1e280-4384-11eb-80ae-a45733c89cd4.png">
