### ISSUE TITLE
Question about open issues

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1665]
Hi, I see the README.md has been recently updated to indicate that issues should be reported by email. Can someone from IEX please clarify if we are supposed to send emails for previously reported yet still open issues on here? For example, I have [14 open](https://github.com/iexg/IEX-API/issues/created_by/MorningSleeper) so would like to know if I should now send 14 emails instead of waiting for a reply on here, thanks.

**Comment by jesseorosz** [comment]
I've been using the service for 18 months now.  I thought it had promise at first and had patience however it's gotten worse by time. Their so called "platform upgrade" on December 1st is a train wreck.

The reason they want issues submitted over email now is because it's gotten out of control.  I have a feeling they'll be killing off the product soon.

**Comment by adamwozney-iex** [comment]
Hey @MorningSleeper - Sorry for any confusion. If you could email support@iexcloud.io with the email address associated with your IEX Cloud account and a link to your open issues on Github, our team will review and respond accordingly.

Going forward, if you're able to send any issue you're having to support@iexcloud.io, we'll be able to better track and respond to your issues. Again sorry for any confusion and thank you for your patience.

**Comment by jesseorosz** [comment]
Just what I was looking for - evidence of IEX deleting comments on GitHub

Thanks!

**Comment by MorningSleeper** [comment]
Ok, no problem, will send email, thanks for the clarification.
