### ISSUE TITLE
[Data] iexId is missing for newer listings like ABNB / DASH

### ISSUE THREAD

**Issue by jkotchoff** [iexg/IEX-API#1678]
## Summary
The [symbols](https://iexcloud.io/docs/api/#iex-symbols) API (ie. `https://cloud.iexapis.com/stable/ref-data/symbols?token=TOKEN`) is missing the iexId field for newly issued securities like `ABNB` and `DASH`.

In the past, this feed always provided an iexId for every listing.

**Comment by McQgit** [comment]
@jkotchoff While you wait for official IEX response, you should know they are deprecating the iexID field. See:
https://intercom.help/iexcloud/en/articles/4529082-iex-cloud-s-2020-data-upgrade

Which says:
The "iexID" field will be deprecated in 2021. We’re developing a comprehensive reference data model for early 2021, which will expand the number of identifiers you can use to query data on the platform. As a part of this update, we will ultimately retire the use of iexID as a symbol identifier in early 2021. To give you more time to migrate from its usage, we’ve temporarily restored access to iexID. In the interim, we suggest migrating to the use of FIGI as an identifier for stocks and ETFs, or CIK for mutual funds. Our team will keep you up to date on timelines for introducing new identifiers and fully moving away from iexID, so that you can prepare accordingly

**Comment by timpaine-iex** [comment]
@McQgit thanks for responding@ @jkotchoff this is indeed the answer, [we're moving away from `iexID` as we migrate to a more generic solution](https://xkcd.com/927/).

**Comment by jkotchoff** [comment]
Thanks for this! It would be great if the [#international-symbols documentation](https://iexcloud.io/docs/api/#international-symbols)  was updated to reflect this.

**Comment by timpaine-iex** [comment]
@jkotchoff I will make sure its updated, thanks for pointing out!

**Comment by jkotchoff** [comment]
@timkpaine, something I'm unclear about here, the _figi_ field isn't enforced as unique in the IEX symbols feed and so I'm not sure how it can replace the iexID as an identifier for common stocks?

Specifically, there are currently 54 figi duplicates in the feed such as:
```
BBG000BBQ281: NAS:ENVB,NAS:AMRH,NAS:ENVB
BBG00KB1G6Y2: NAS:BFI,NAS:OPES
BBG00KFN07H4: NAS:BFIIW,NAS:OPESW
BBG00M0VJ3R6: USAMEX:BMTX,USAMEX:MFAC
BBG00M14DKQ4: USAMEX:BMTX+,USAMEX:MFAC+
BBG00PV4MRF1: NAS:BTRS,NAS:SMMC
BBG00PV4Q0L9: NAS:BTRSW,NAS:SMMCW
BBG000BVJ702: NYS:CSR,NYS:IRET
BBG00XRJLY53: NYS:CTAC=,NYS:CTACU
BBG00QJ46QF3: NYS:DFNS=,NYS:DFNSU
```

**Comment by timkpaine** [comment]
@jkotchoff as an aside, you can lookup via the [openfigi website](https://www.openfigi.com). 

The first item in your list: https://www.prnewswire.com/news-releases/ameri-holdings-completes-spin-off-and-tender-offer-changes-name-to-enveric-biosciences-and-begins-trading-on-the-nasdaq-under-the-symbol-envb-301199647.html

The second item in your list: https://finance.yahoo.com/news/burgerfi-goes-public-following-completion-120000926.html

Looking at the names, the rest will likely also be reverse mergers or symbol changes. So the behavior here is correct, the mapping from symbol to security is many-to-one. 

Digging a bit into the symbols results:
<img width="1018" alt="Screen Shot 2021-01-16 at 4 21 19 PM" src="https://user-images.githubusercontent.com/3105306/104823260-e639bb00-5816-11eb-8f88-edbd73d6fee8.png">

12/31 is the last day Ameri Holdings Inc was around, and 12-17 was the last day Opes Acquisition Corp was around.

**Comment by jkotchoff** [comment]
Fantastic @timkpaine, thanks for clearing that up!! This type of context would also be helpful when the IEX documentation is updated.
