### ISSUE TITLE
[Data] Prices on some securities at London Stock Exchange (LSE) is outdated

### ISSUE THREAD

**Issue by alreadygreen** [iexg/IEX-API#1709]
I requested quote for VWRL-LN ETF at LSE. But price for this ETF has been updated on 27 November 2020!

Executed request:
https://cloud.iexapis.com/stable/stock/market/batch?symbols=VWRL-LN&types=quote&token=...

Do you plan to provide up to date data for exchanges outside of US?

**Comment by timpaine-iex** [comment]
I'm assuming you're actually looking for `VWRL-NA`?

**Comment by timpaine-iex** [comment]
`VWRL-SE` is ok as well

**Comment by alreadygreen** [comment]
Yep, -NA and -SE look fine. But -LN is way out of date.

I also noticed that data for EIMU-LN doesn't look right. It shows latest price: 4.074. On official [website](https://www.ishares.com/uk/individual/en/products/295689/ishares-core-msci-em-imi-ucits-etf) it's 5.69. And it was above 5 since November 2020.

But it's not that bad for all securities from LSE. WLDS-LN looks correct to me.

**Comment by alreadygreen** [comment]
@timpaine-iex does it make sense to wait for proper data for LSE or it's better to look for another API for non-US markets?

**Comment by timpaine-iex** [comment]
We have proper data for a LSE and a large number of non-US markets, but you do what's best for you and your data budget.

**Comment by alreadygreen** [comment]
It looks like that your data is outdated for months for many popular ETFs on LSE: VWRL-LN, IH2O-LN, INRG-LN, IWDP-LN. For some other ETFs it just have some random values. Might because of wrong currency. I found it unusable for: SMH-LN, VOLT-LN, ESPO-LN.

If it's not a priority for iex to provide upto date data for UK market then maybe it's not the best tool for UK investors. Thanks for the clarification.

**Comment by timpaine-iex** [comment]
You should evaluate and determine the right tool for your use case, I'm not familiar with what the ecosystem looks like in EMEA but our datasets tend to skew heavily for US (e.g. fundamentals, etc). There are plans to expand which you can see on the roadmap, though many of these probably will focus initially on Canada/NA markets. 

We have up to date data for all these tickers, our suspicion is because they're just proxies for securities listed in other markets there is some currency mismatch and they output isn't being updated. We're looking, but prioritization/SLA is dictated by tier (https://iexcloud.io/pricing). If you're a paying customer I recommend sending an email to support so its tracked and prioritized accordingly.

**Comment by scotNZ** [comment]
@timpaine-iex 

Just some feedback for you. 

We are currently evaluating IEX as a source of global financial data. The API is well constructed (mostly) but you seem to be saying that we shouldn't expect the same level of reliability for non-NA data as might be expected for NA data. This is a very unusual attitude in a commercial domain where reliability is crucial.

Can I suggest that if you offer data from a market it must be reliable. Honestly, anyone operating in this area will be horrified to hear you so relaxed about errored data since the follow on consequences can be dire. If I was you and had just heard that one of my API's was errored, I have it down immediately until rectified. 

Its ok if you don't have a priority outside the US - just don't include data you can't assure. 

A relaxed attitude to false data is not well tolerated in the financial industry. It's a cultural thing born of much pain. Unreliable data is worse than useless.

**Comment by timpaine-iex** [comment]
@scotNZ I never said anything about reliability, just coverage. I am very familiar with the financial industry and data, but your comments suggest you are not. I encourage you to research more into data errors, in particular for major providers.

**Comment by scotNZ** [comment]
"I never said anything about reliability, just coverage"

That makes no sense and is not how I interpret your responses. This issue started with a report of stale data for VWRL-LN persisting for some 5 months.

"We have up to date data for all these tickers"

Well that doesn't sound like a coverage issue and just begs the question.

"I am very familiar with the financial industry and data, but your comments suggest you are not".

Not so but lets try to make this discussion productive. 

Can I assume if a London ticker is included in your ref-data api (and its enabled), I should expect that all relevant api's will operate as expected with up to date data?

What I am trying to establish is in fact IEX reliable coverage for offered symbols (which is how I came across this thread).

**Comment by timpaine-iex** [comment]
> Can I assume if a London ticker is included in your ref-data api (and its enabled), I should expect that all relevant api's will operate as expected with up to date data?
> 

Correct, we are receiving up to date data from upstream for everything listed in ref data (as a general statement of course, our upstream providers also have frequent data problems as is common for every provider in this space). There are other influencing factors of course (some data we receive we cannot redistribute or are midway through negotiating contracts with exchange, etc etc). The speculation is that there is a bug somewhere in the quote construction due to the tendency of cross listed European ETFs to quote on local exchanges in non-local currencies. 

However, to the larger question, `quote` is designed to be a real time stock quote, and we do not have coverage for real time data from international exchanges publicly (yet). So if you're using `quote` for an international symbol, you probably wanted to use `chart`/`historical-prices`. Thus while there's an issue with `quote` which we know about and are looking into (respecting the prioritization and SLAs based on affected users), `chart` is the more appropriate endpoint to be using for this case.

**Comment by timpaine-iex** [comment]
>  If I was you and had just heard that one of my API's was errored, I have it down immediately until rectified.

Take a look at the refdata.

**Comment by scotNZ** [comment]
Ok, great.

I think you also have a problem with historical chart data.

I think I'm right in saying that VWRL-LN has been removed from your London symbol list but EIMU-LN and WLDS-LN remain listed and enabled (just examples cited above).

I'm not that familiar with your historical chart api but I can't seem to extract anything recent for EIMU-LN and WLDS-LN?

https://cloud.iexapis.com/stable/stock/EIMU-LN/chart/date/20210503?chartByDay=true&token=

Empty array?

Seems to be working for April dates.

**Comment by timpaine-iex** [comment]
@scotNZ May 3 is a bank holiday no? https://www.tradinghours.com/markets/lse/holidays

**Comment by scotNZ** [comment]
@timpaine-iex

The perils of dates and holidays ....

I'll stick with the chart api for now - EOD is our primary interest.

thanks

**Comment by timpaine-iex** [comment]
@scotNZ 😂 the joys of financial data

**Comment by scotNZ** [comment]
@timpaine-iex

Couple more I came across that seem to offer no EOD data:

PLI-LN, GVC-LN

**Comment by timpaine-iex** [comment]
`date` is `2020-12-11` for `GVC` and `2020-12-17` for `PLI` so I wouldn't expect them to have data.

**Comment by timpaine-iex** [comment]
If you query `time-series` with a range that is valid for those symbols' refdata, you should get data e.g. `https://cloud.iexapis.com/stable/time-series/HISTORICAL_PRICES/GVC-LN?range=Q32020&limit=1&token=...`

**Comment by timpaine-iex** [comment]
@alreadygreen pushed a fix for the lse etf problem today, mind taking a look and seeing if you see any more problems?
