### ISSUE TITLE
Trying to import just changepercent

### ISSUE THREAD

**Issue by DAK7777** [iexg/IEX-API#1729]
When I use the following it returns N/A.  Is there another formula string I should be typing in?

=IMPORTDATA(("https://cloud.iexapis.com/stable/stock/symbol/changepercent?token="Token"))

**Comment by McQgit** [comment]
@DAK7777   Try something like:
https://cloud.iexapis.com/stable/stock/MSFT/quote/changePercent?token=X

Notes:
1) changepercent is case sensitive - should be changePercent per docs
2) You were missing 'quote' qualifier 
3) You should provide actual symbol you were trying rather than just showing `/symbol/`
