### ISSUE TITLE
[Data] News credits changed from 1 to 100 ?? Is it by mistake or intentional ?

### ISSUE THREAD

**Issue by dgurudot** [iexg/IEX-API#1736]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Email account associated with your IEX Account**

**Date/time of the issue**
July 16

**What you did**
Sent News API request

**What you expected to happen**
1 credit per API calls.

**What actually happened**
100 credit per news API call.

**API Url (if applicable)**
GET /stock/{symbol}/news/last/{last}

**Additional relevant information**

**Comment by timpaine-iex** [comment]
Yep was announced via email a few weeks back:
https://intercom.help/iexcloud/en/articles/5376501-updates-to-billing-and-credits-july-2021

**Comment by timpaine-iex** [comment]
Because of these updates, we’re able to lower the data weight for over 30 frequently used endpoints: 
- Historical News: From 5,000 to 100 credits 
- Financials as Reported: From 5,000 to 1,000 credits 
- Advanced Fundamentals: From 75,000 to 30,000 credits 
- Forex Real-time Streaming: From 500 to 10 credits 
- Forex Latest Currency Rate: From 500 to 10 credits 
- Forex Currency Conversion: From 500 to 10 credits 
- Forex Historical Daily: From 100,000 to 10 credits 
- End-of-Day Options V2: From 1,000 credits per symbol per date to 10 credits per record 
- Daily Treasury Rates: From 100 to 10 credits 
- All Commodities Endpoints: From 1,000 to 10 credits 
- All Economic Data Endpoints: From 1,000 to 10 credits 

Note that a handful of endpoints will have increases in data weights. See below: 
- Company: From 1 to 10 credits 
- News: From 1 to 100 credits 
- Streaming News: From 1 to 100 credits

**Comment by dgurudot** [comment]
10 and 100 times increase for commonly used endpoint like news is outrageous in my opinion.

You can never use the free and launch plan now with this change and you have just created a big barrier to use IEX even during development.

You might as well remove these plans because these new updates doesn’t make sense now.

I am thinking of moving away and dropping my plan to use IEX because credits just gets used immediately with this change.

**Comment by joshuablackburn-iex** [comment]
The new price is $0.0001, so let's keep things in perspective. Our current plans include cloud cache (for free!) which means you only pay this new rate the first time you pull the data. You'll need to pull 500,000 news articles before you even approach the price of our nearest competitor.
