### ISSUE TITLE
How to get current price of a specific contract symbol Options v2

### ISSUE THREAD

**Issue by Spencer-Villarreal** [iexg/IEX-API#1757]
Hello,

I have been sitting here for a couple of days trying to figure out how to get the current price of a specific contract symbol or at least the last end-of-day price.

Today is November 4, 2021 and whenever I query the specific symbol it gives me the price the contract was on October 11, 2021.
End-point I am using: https://cloud.iexapis.com/stable/options/AMC20211217P00050000/chart?token=pk_xxxxxxxxxxxxx

Adding "range=1d", "range=Today", "range=Yesterday" does nothing. 

With this new Options v2 endpoint can we get the current price/eod price? or can we only get what the price was a month ago?

Clarification:
- Using: "https://cloud.iexapis.com/stable/options/AMC20211217P00050000/chart?token=pk_xxxxxxxxxxxxx" gives me the price from a month ago
- I want to get the current price or at least what the contract closed at yesterday

**Comment by timpaine-iex** [comment]
this query is fine:
https://cloud.iexapis.com/stable/options/AMC20211217P00050000/chart?token=pk_xxxxxxxxxxxxx

if you want "last record" from time-series (the latest calendar record we have stored prior to the time of API request) its just:
https://cloud.iexapis.com/stable/options/AMC20211217P00050000/chart?token=pk_xxxxxxxxxxxxx&last=1

There's been a problem with options data for ~1 month now, days load sporadically which is why the last data is October 11 and I believe the record before that is September some time, its being investigated.

**Comment by Spencer-Villarreal** [comment]
@timpaine-iex Oh okay, I did not know that the time-series goes at the end after the token. I thought everything would have to be place before the token parameter.

Thank you for your response, do you have any estimate as to when the problem will be fixed?

**Comment by timpaine-iex** [comment]
@Spencer-Villarreal they're just query parameters so the order doesn't matter (this is just HTTP spec). 

Timeline is "urgently", obviously this is a big annoying problem. Please feel free to ping support and they'll make sure to comp any credits you wasted on the bad data.

**Comment by Spencer-Villarreal** [comment]
@timpaine-iex Okay thank you so much!

**Comment by timpaine-iex** [comment]
@Spencer-Villarreal no problem, apologies for the inconvenience!
