### ISSUE TITLE
Definitive Open Price

### ISSUE THREAD

**Issue by radikal9** [iexg/IEX-API#180]
## Summary
Is there way to know definitively what the OPEN price is? We have been trying to get an accurate OPEN price for some time now but it is hard to nail down. Our developers gave us the following example for the stock TSN on January 11. At 9:30 AM using /quote the OPEN response was $81.99 but the first price from /quote we got was $80.96 and when we used the API, the first value we got there was $81.05 which according to Yahoo (and I realize that they may have slightly different opening prices) was the correct value. Is there any way to have a null value till you get the opening price (which I understand is not always at 9:30:00 AM)?

### What you expected to happen
Have the OPEN price at /quote to be the open price of the stock.

**Comment by yuvalshtemer** [comment]
I'm also having an issue with the open price, is there any update on this or on what time open price updates?

**Comment by joshuablackburn-iex** [comment]
In the /stock/quote endpoint, 'open' and 'close' represent the official open and close price from the listing venue.  The reason you receive prices before an open is because other venues can trade a stock as early as 4am, and on IEX we start trading at 8am.  Additionally, stocks do not always open at 9:30:00.  The time can vary depending on the exchange.  We include a timestamp with the open and close so you know if the value is for today.

**Comment by evancarter-iex** [comment]
Fixed with IEXCloud. https://iexcloud.io
