### ISSUE TITLE
market previous call returning a random number of stocks

### ISSUE THREAD

**Issue by russelljjackson** [iexg/IEX-API#189]
## Summary
Market/previous call not returning data for all stocks, but instead returning a variable number of stocks.

### Date/time of issue
1/22/2018 11:05PM EST

### API URL

https://api.iextrading.com/1.0/stock/market/previous

### What you expected to happen
See previous days data for ALL stocks

### What actually happened
Returning a somewhat random number of stocks, sometimes all the way thru the "T" symbols, sometimes just some of the symbols.

**Comment by mwahal** [comment]
Happening since last night, stuck at symbols through "C". This is the last one, "symbol":"CVLY".

**Comment by mwahal** [comment]
Yep, still happening as of Jan 24 6:50PM Pacific. Same stuck at CVLY.

**Comment by mguardos** [comment]
Issue can still be replicated. I was only able to get the entire list of stocks last Friday (02/16/18). Since then, the list stops sometimes at a certain stock for quite a while. At this moment (02/19/18 - 11:57 AM EST), it is stopping at BPFHP
Interestingly, it seems to stop at the same stock for a certain time of period regardless of how many times I try. Then it jumps to another 'last' stock, sometimes sooner and sometimes later in the list, and then all executions get stopped at the same stock for another period of time

**Comment by mguardos** [comment]
If it helps tackling down this issue, I just tested the same call (02/20/18 - 6:27 PM EST) and the last stock is  TCBI

https://api.iextrading.com/1.0/stock/market/previous

**Comment by mguardos** [comment]
And finally it worked fine (all stocks are returned) after running the same call on 02/20/18 - 11:49PM EST
