### ISSUE TITLE
Stocks/Chart endpoint doesn't return unadjusted close data

### ISSUE THREAD

**Issue by vitekm2016** [iexg/IEX-API#194]
## Summary
The documentation available at https://iextrading.com/developer/docs/#chart shows in example JSON return a response key called "unadjustedClose". However, this key is not returned if you actually request it from the API.

**Comment by optionsgithubuser** [comment]
Any update on this?

**Comment by hesoun** [comment]
Any update please? unadjustedClose would be very welcome. Thanks

**Comment by JohnRobson** [comment]
@joshuablackburn-iex , any update?! Please, add "unadjusted close price".

**Comment by evdubs** [comment]
I, too, would like to have a historical source for unadjusted data. It allows me to just query the API once and save the data locally rather than query the API every time I need the data. Saving adjusted data gets messy the moment another split/dividend happens. 

I am currently maintaining a [Racket library](https://github.com/evdubs/iex-stocks) to extract from the IEX Stocks API, and I would love to add a component that can retrieve historical unadjusted prices. @joshuablackburn-iex will you please comment on this feasibility? Perhaps this can be a v2 addition?

**Comment by evancarter-iex** [comment]
https://iexcloud.io/docs/api/#historical-prices has this data/

https://iexcloud.io to sign up.
