### ISSUE TITLE
Allow more than 5 years of historical Chart Daily data query

### ISSUE THREAD

**Issue by absinha18** [iexg/IEX-API#217]
## Summary
Is there a way to request for chart data for more than 5 years ?

**Comment by inVisement** [comment]
Please add chart for max end-of-day price data that you have
/stock/aapl/chart/max

Or have the possibility to download them. Thanks.

**Comment by redmondmikemu** [comment]
+1 .  I agree with inVisement.  Having complete historical data would be very helpful for analysis and charting.  Now, I get historical data (5+ years old) someplace else and then have to stitch the data together since they are in different return formats.   It would be great to have full history in one call.  Many thanks.  btw.  thanks guys - great service you have.

**Comment by evancarter-iex** [comment]
IEXCloud has 15 years of historical data. https://iexcloud.io
