### ISSUE TITLE
Batch request returning ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by LeoAlvarez** [iexg/IEX-API#320]
## Summary
From command line or from browser, batch call keeps timing out

## Details
An example call:
https://api.iextrading.com/1.0/stock/market/batch?symbols=ypf,yrcw,yum,yumc,yy,z,zayo,zbh,zbra,zion,zs,zen,zoes,zto,ztr,zts,zuo,xme,zumz,zurvy&types=quote,chart&range=1d&last=5

In Chrome, getting
This site can’t be reached
api.iextrading.com took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

### Date/time of issue
6:56am PST

### API URL
This site can’t be reached
api.iextrading.com took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

### What you expected to happen
I expected a normal return from all my calls (they're a series of 5 batched requests), but keep getting the calls timing out.

### What actually happened
Keeps timing out

### Other Information (sample code, links, etc.)
This started happening yesterday afternoon, 20 minutes before the close

**Comment by joshuablackburn-iex** [comment]
We had to block these requests due to impact on other users.  We observed your API calls every 5 minutes, and it appears you want chart data only for the last 5 minutes.  The URL you are using fetches all data, so it was fetching up to 390 data points for every symbol at one time.  

The URL you want to use is: https://api.iextrading.com/1.0/stock/market/batch?symbols=ypf,yrcw,yum,yumc,yy,z,zayo,zbh,zbra,zion,zs,zen,zoes,zto,ztr,zts,zuo,xme,zumz,zurvy&types=quote,chart&range=1d&chartLast=5

Notice that for charts you should use chartLast.

Also, I'd recommend spreading out your batch calls rather than putting them in a tight loop.  Once you've updated your call, let me know and we will reenable your access.

**Comment by LeoAlvarez** [comment]
Got it, thanks! 

Call is updated, please reenable my access

**Comment by LeoAlvarez** [comment]
I'll try it out, thanks.

That param isn't in the docs, btw, so I didn't know it was available:
https://iextrading.com/developer/docs/#batch-requests

**Comment by LeoAlvarez** [comment]
can i do every 10 minutes? it's a cron job that calculates intraday technicals. please let what if that rate works.

**Comment by joshuablackburn-iex** [comment]
It is less about the amount of time between jobs, and more about the number of calls (symbols * data points) at the same time.  We use different methods with our 3rd party developers such as spacing out jobs by range of symbols, or ensuring no more than N number of calls go out at the same time.

**Comment by LeoAlvarez** [comment]
hmm, i understand. i'm calling 100 symbols at a time. i do need to grab all the symbols (it's a huge calculation), should I call 75 or 50 at a time instead?

**Comment by joshuablackburn-iex** [comment]
Is this just one batch call with 100 symbols?

**Comment by LeoAlvarez** [comment]
no, it's multiple batch calls with X (in this case, 100) symbols. i can change the number in each batch call, but that means more batch calls.

**Comment by joshuablackburn-iex** [comment]
100 symbols per batch is fine.  It's the number of batch calls at once.  Doing all 8500 symbols at the same time has a noticeable impact on the system.  Dropping that to 5-10 per second rather than 85 per second should help a lot.  Down the road we will offer this as a push service to avoid this polling, but for now we need to keep things spaced out a bit.

**Comment by LeoAlvarez** [comment]
it's not 8500 symbols, it's under 3000 :D i'll put in some throttling, then -- i have another that gets historical which is throttled, so it never makes more than 20 calls at a time. all this is in node, btw.

can i get access turned on again? i'll work on this, might take me an hour, though.

**Comment by LeoAlvarez** [comment]
ok, thanks... not working yet, added the throttling, but something still not right.

**Comment by LeoAlvarez** [comment]
hmm, might take longer, guess i'll shut it down for the day, need more time.

**Comment by LeoAlvarez** [comment]
looks like i finally have it -- i can throttle each call by milliseconds. i have it set for a call every second. it's under 30 calls, every 5 minutes. will that work for iex? or should i do every 2 seconds?

**Comment by evancarter-iex** [comment]
@LeoAlvarez 2 seconds is better. Thanks

**Comment by LeoAlvarez** [comment]
actually, thank you. this 'forced' me to change the fetch algorithm to something a lot more flexible.

**Comment by evancarter-iex** [comment]
@LeoAlvarez Glad to help. Thanks for using the API.
