### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by ksallberg** [iexg/IEX-API#347]
## Start using version numbers

Currently, the API documentation mentions "1.0" over and over again, and increments the date afterwards.

This makes it difficult to say that your API client supports a certain version of IEX API. It would be better if the version number was something like X.Y.Z and that it was incremented in a logic fashion.

**Comment by SeamusBoyle** [comment]
Have there been any breaking changes?

**Comment by ksallberg** [comment]
@SeamusBoyle Not any breaking changes that I know of. However I think it is sound software engineering to have release numbers that are increased and don't just overwrite 1.0 again and again

**Comment by SeamusBoyle** [comment]
I was hoping there was breaking changes, for precedence. My 1d candle parser is getting ugly handing the new fields that have been added but historical data doesn't get updated with new fields. E.g open/close was added but is only available on new data and only if any trades occured, average is the fallback and it is always present event when no trades occur. This means you need to check every candle (until the first trade) and can't just peak at the first element.

I went a bit OT. Regarding versioning could just use the date as the version and the '1.0' as the product. So then you have 20180523 that's more useful than 1.0.29 since there will probably never be a breaking change without bumping the major number, the changelog would ideally show dates in the same format.

Anyway, I just wget the whole docs page and include next to (same repo as) the client implementation.

**Comment by joshuablackburn-iex** [comment]
@ksallberg I definitely agree with your regarding version numbers.  Version 1 is a bit messy in this regard.  We are working version 2, and a lot of these little issues will be resolved.

@SeamusBoyle Sorry for the inconsistent 1d data.  This is something I'm working to resolve as well.  

The next version will have a better versioning system.

**Comment by ksallberg** [comment]
Ok thanks @joshuablackburn-iex I will close this ticket now then
