### ISSUE TITLE
How to use IEX Real Time Price with ASP.Net C# (webform mvc both

### ISSUE THREAD

**Issue by raheeldeveloper1984** [iexg/IEX-API#358]
## Summary

How can I use API in asp.net with web forms as well as MVC, Is any sample program available for this, Kindly help me I am a beginner

**Comment by mitalpha** [comment]
To get intraday streaming IEX data use their websocket endpoint for subscription

with C# 
https://github.com/Quobject/SocketIoClientDotNet
with Java
https://github.com/socketio/socket.io-client-java

Follow their sample https://iextrading.com/developer/docs/#websockets using SocketIoClientDotNet instead of JavaScript, that's it.
