### ISSUE TITLE
Is the market overview a valid endpoint that can be used in production? 

### ISSUE THREAD

**Issue by king3andre** [iexg/IEX-API#419]
## Summary

Is the market overview a valid endpoint that can be used in production? It is not listed in the API docs. However, it is being used for the IEX stocks app with some components that I find useful.

## Details

I'm particularly interested in the components that are listed for "Earnings Before Open", "Earnings After Close", "Ex-Dividends", and "IPO Calendar"

### Date/time of issue

7/10/2018

### API URL

https://api.iextrading.com/1.0/stock/market/overview

**Comment by bkcollection** [comment]
Agree with @king3andre . It will be better to have separate API for "Earnings Before Open", "Earnings After Close", "Ex-Dividends", and "IPO Calendar".

There is a lot of data mixed in the overview API

**Comment by joshuablackburn-iex** [comment]
It is not something we are currently advertising in our documentation.  There are some endpoints we construct for the Stocks app in order to test new data.  We test on ourselves before publishing to API users.  We want to make sure we don't miss anything.

@bkcollection Those endpoints do exist, I will just need to update our documentation once I feel comfortable everything is working as intended.
