### ISSUE TITLE
Did we get blacklisted?

### ISSUE THREAD

**Issue by rterp** [iexg/IEX-API#43]
From our office we are getting  Connection Timeout Errors when attempting to access the IEX REST and websocket endpoints.  However when I access from my home PC I am able to get to them without any issues.  We are able to get to other sites from the office so it doesn' appear to be an Internet access related issue.  How can we tell if we were blacklisted?

**Comment by joshuablackburn-iex** [comment]
Yesterday we observed a single IP making at least 400 websocket connections per second which caused tons of 502 errors and response times to exceed 10 seconds. After several hours, we decided to block this IP since this is not a normal way of using websockets.  A single websocket connection can be used to receive data for all symbols.  Our HTTP API endpoints are built to handle many requests per second, but Websockets are intended to be long lived.  If this is your IP, we can unblock as long as the code is fixed.  If we continue to observe the same activity, we will need to block to ensure a good experience for our other users.

**Comment by rterp** [comment]
?I talked to our staff, and it very well could have been us, external IP address 24.18.146.27



I'll talk to the developers and make sure the program is no longer running.


thanks,

-Rob


________________________________

**Comment by joshuablackburn-iex** [comment]
Thank you.  We don't mind handling a ton of requests, but the Websocket requests didn't seem normal.  You can email us at api@iextrading.com if you'd like to work through ways to optimize calls to the API.  Let us know when the program is off and we will reenable the IP.

**Comment by rterp** [comment]
?Thank you,  the program is no longer running.

________________________________
