### ISSUE TITLE
Regarding Commercial Use and the lifetime of Version 1.0

### ISSUE THREAD

**Issue by nazca777** [iexg/IEX-API#629]
So I sent a message to api@iextrading.com a while back with these questions but got no response.
So I have been working on a mobile app that lets users research, create a watchlist, get directional forecasts, and scan the market, and I have been able to do this thanks to the API, so thank you!
Anyways, I am using the 1.0 API and I wanted to know these two things:
1. Can I use this for a commercial app? The app charges for forecasts and scans, where I run algorithms on the data to accomplish, Im not reselling/redistributing the data itself. I looked for an answer regarding commercial use on the site anywhere.
2. With the Cloud API being pushed, how long will the V1.0 API be around? 

Thank you in advance!

**Comment by joshuablackburn-iex** [comment]
The IEX API (v1) will continue to be available, but we will phase out 3rd party data on June 1st. We are going to make a detailed post of what is going away, but essentially everything under "Stocks" will be dropped. We are no longer proceeding with that 3rd party provider since we have been able to bring professional quality data to IEX Cloud.

IEX Cloud will have the same IEX data as v1, and it will remain free for all users.

One of the unique features of IEX Cloud is that commercial use of data is base feature for all paid users. Free accounts have access to all the same professional grade data, but for personal use only. We just ask that everyone respect these rules so we can continue offering all this data at unprecedented prices.

Personal, non-commercial use means any use that is only for yourself.  For example, if you are using IEX Cloud Data for your own personal investments, and you hope to make money doing so, you may use the free Start plan.  
 
Commercial use means any use where IEX Cloud Data is incorporated into or used by an income-generating product, even if you are not distributing any IEX Cloud Data, and any use by a business.  For example, if you are using IEX Cloud Data in an app that is income-generating, through advertising, sales, or otherwise, you may NOT use the free Start plan and must subscribe to the Launch or Scale plan.
