### ISSUE TITLE
Incorrect quotes after market hours

### ISSUE THREAD

**Issue by simpsonjoshua** [iexg/IEX-API#64]
I've noticed that after market closes, calling the same ticker multiple times will sometimes return different results. Below is an example where they were called roughly one minute apart and well after market hours. 

<img width="1098" alt="screen shot 2017-11-07 at 1 33 00 am" src="https://user-images.githubusercontent.com/30989843/32480242-a4f68342-c35b-11e7-967e-e91f9686b4ce.png">

**Comment by myvaluealerts** [comment]
jcape, that's very likely and is an issue with nearly all data providers.  often trades will continue to filter in for up to an hour.  then, before the market opens the previous days data is cleared and price & volume go to zero.  Worst, not all stocks start trading at the same time in the morning.  many stocks don't start trading for 20 - 30 minutes after market open.  on my website (myvaluealerts.com) I delay pulling data for 30 minutes after the market opens and stop 5 minutes before market close.  (my site is currently down as I try and figure out how to switch from yahoo data to iextrading.com data.

**Comment by jcape** [comment]
@simpsonjoshua Could you share when this was called (i.e. the exact time in US EST)? Also, I assume you were looking at https://api.iextrading.com/1.0/stock/market/batch?types=quote&symbols=ZION to see this? Thanks,

@myvaluealerts For trades (i.e. not the closing price), that is to be expected. NMS (protected market) hours are 09:30-16:00 (all times US ET), but the SIP (the "tape") is running from 03:00-20:00, and IEX is trading 08:00-17:00. Could you create a new issue to discuss any issues you're having unrelated to closing price changing in the postmarket?

**Comment by simpsonjoshua** [comment]
I don't know the exact timestamp of when it was called. That specific call was around 1:20 AM EST but it was happening throughout the night. I was calling it every 30 seconds. Sometimes it would be fine, other times it would be different. And yes, that was the URL.

**Comment by myvaluealerts** [comment]
Could you create a new issue to discuss any issues you're having unrelated to closing price changing in the postmarket?
Sure;  however, be aware that if the price changes then all the items flagged above will also change:
(Market Cap; PE ratio; ytd Change; change; percent change)/.  even a few cent change in price will ripple to all of the items flagged with the original post.

**Comment by jcape** [comment]
@simpsonjoshua  Thanks for reporting this, it looks like you just happened to hit the API in the couple hours of the early morning when this particular issue could happen.

A couple lines of code assumed that our previous-day-close prices (which is sourced from a third party) was updated because it was a new day, but the scheduled task to handle this update was still running in the background. The first query contains the "stale" PDC data (that is, the closing price noted is from Friday, not Monday), and the second query contains the correct, post-update data, including Monday's closing price. We're rescheduling the task which updates this information to run earlier, which will minimize the likelihood of recurrence.

I'll close this issue once we've rolled out the new schedule, and this has been deployed and this is fixed.

**Comment by jcape** [comment]
@simpsonjoshua Thanks for letting us know about this issue, the new schedule has been deployed and operating for the last couple days. Feel free to add a new comment to this issue if you see this problem again.
