### ISSUE TITLE
IEX Cloud signup now available

### ISSUE THREAD

**Issue by joshuablackburn-iex** [iexg/IEX-API#655]
Everyone is now able to sign up for IEX Cloud. 

https://iexcloud.io

**Comment by yccheok** [comment]
Hi,

From https://github.com/iexg/IEX-API/issues/557 , I understand IEX plan to retire free V1 API, and urge all developers move to to paid V2 API, by May 2019.

Since, May 2019 is pretty short notice period, for us to perform all necessary code migration and testing, would IEX consider to continue support free V1 API, till next year?

Thank you.
