### ISSUE TITLE
Missing ECC dividend data in Iexcloud

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#660]
## Summary
Not all dividend data. 

ticker: ecc

request: https://cloud.iexapis.com/beta/stock/ecc/dividends/5y?token=MY_TOKEN
response: []

nasdaq: https://www.nasdaq.com/symbol/ecc/dividend-history

**Comment by evdubs** [comment]
In addition, some dividends are coming back with dates 0000-00-00. For example:

https://cloud.iexapis.com/beta/stock/abb/dividends/5y?token=MY_TOKEN

This gives me the following dividends:

```
"ABB":{"dividends":[
{"exDate":"2015-05-04","paymentDate":"2015-05-14","recordDate":"0000-00-00","declaredDate":"2015-04-30","amount":0.72,"flag":"Increase"},
{"exDate":"2014-05-05","paymentDate":"0000-00-00","recordDate":"0000-00-00","declaredDate":"2014-04-30","amount":0.7,"flag":"Increase"},
{"exDate":"0000-00-00","paymentDate":"0000-00-00","recordDate":"0000-00-00","declaredDate":"2016-04-22","amount":0.74,"flag":"Increase"},
{"exDate":"0000-00-00","paymentDate":"2017-04-21","recordDate":"0000-00-00","declaredDate":"2017-04-14","amount":0.76,"flag":"Increase"},
{"exDate":"0000-00-00","paymentDate":"2018-04-06","recordDate":"0000-00-00","declaredDate":"2018-03-29","amount":0.78,"flag":"Increase"}]}
```

Hopefully this can be corrected as well?

**Comment by evancarter-iex** [comment]
@evdubs 
@theofficejackpot  
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
