### ISSUE TITLE
Dividend Info

### ISSUE THREAD

**Issue by barrett77** [iexg/IEX-API#71]
I see that you have some dividend info, but it seems like it is historical only. 
Would you be able to pull upcoming payment date and current dividend as opposed to the last dividend and last payment date? This is helpful in calculating dividend increases as well as when you will receive a dividend from a company. 

Thanks!

**Comment by myvaluealerts** [comment]
Good point:  I too am looking for 1,2,3, 7 and 8 below.
IEX currently supplies .  1, 3, 7 & 8

This data is usually pretty easy to come by:
1). last ex-dividend date     2).  last date of record      3). last payment date.    

The following data is not readily available until the company releases it, but it would be nice if IEX could reserve data fields for this data once it is it is released.
4). next ex-dividend date      5).  next date of record     6). next payment date 

Other dividend data fileds are :
7) last dividend amount ($) paid. and  
8) Current dividend yield based on last div amount (%) 
9) Next dividend amount($) 

It would be nice to have a field to hold "next dividend amount ($)" to address situations where companies raise and lower the next dividend.  Most companies only pay quarterly so using the "last dividend" data can be very misleading where companies cut the dividend by 75% and you only have "last dividend" as a guide (examples: FGP & TEVA).

Concerning  1). last ex-dividend date     2).  last date of record      3). last payment date.    
These three dates are relevent because: if I sell a stock on or after the "ex-date" I will still receive the dividend on the "payment date".  AND, if I have dividend reinvestment turned on in my trading account, SOME (not all) brokers will go ahead and use the dividend to re-purchase new shares with the incoming dividend.  Which means I will now have to pay a commission (say $20) to sell $25 worth of stock because of the $25 dividend that got reinvested in the stock I jsut sold.

**Comment by joshuablackburn-iex** [comment]
We can look into acquiring this data for all stocks, but as a primary listing exchange, we will provide all of this data for our own stocks.  This is already explained on our page here: https://iextrading.com/listings/daily-list/

We will also provide an API endpoint at https://api.iextrading.com/1.0/ref-data/daily-list/dividends

This will return all upcoming dividends for our listed companies.

**Comment by myvaluealerts** [comment]
joshuablackburn-iex   - take a look at that 2nd link you supplied.  It goes to a blank page.

"We will also provide an API endpoint at https://api.iextrading.com/1.0/ref-data/daily-list/dividends"

**Comment by joshuablackburn-iex** [comment]
@myvaluealerts That's correct.  We **will** provide in the future.  We have not yet listed a company.

**Comment by yccheok** [comment]
@joshuablackburn-iex 

https://api.iextrading.com/1.0/ref-data/daily-list/dividends - I believe this API is gonna to return all company upcoming dividend payment date (If those info are known)

Is it possible to provide an API, where user can specific targeted company? For instance, a user might only be interested in what is the dividend payment date for Mcdonald.

**Comment by joshuablackburn-iex** [comment]
@yccheok This has not been officially released yet.  Once it is, you can expect the same functionality that exists in our other calls, including per symbol queries.

**Comment by ModelsRUs** [comment]
Another enhancement request: Is it possible to add another dividend-related field somewhere for Dividend Frequency - e.g., 3 or "Q" for every 3 months? Thank you.

**Comment by jacinto123** [comment]
Is there any sort of update on this, would love to have this feature.

**Comment by evancarter-iex** [comment]
We have deployed dividend info in IEXCloud. If you havent signed up for the beta, you can here: 

https://iexcloud.io/
