### ISSUE TITLE
Anonymous caller does not have storage.objects.get access

### ISSUE THREAD

**Issue by godsart** [iexg/IEX-API#721]
## Summary
When using 
GET /stock/{symbol}/news/last/{last}
and retrieving "image" value, when I attempt to use the image I receive error instead of an image.

## Details

https://api.iextrading.com/1.0/stock/cgc/news-image/5277617515197222 which forwards to:
https://storage.googleapis.com/iex/api/news/images/5277617515197222.png
which gives the error: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to iex/api/news/images/5277617515197222.png.
</Details>
</Error>

### Date/time of issue
February 25, 2019 all day

### API URL
https://api.iextrading.com/1.0/stock/cgc/news-image/5277617515197222

### What you expected to happen

I expected to see an image. I have used logo api without this particular issue (Example: https://storage.googleapis.com/iex/api/logos/APHA.png)

### What actually happened

I get error instead of image file: 
"Anonymous caller does not have storage.objects.get access to iex/api/news/images/"

### Other Information (sample code, links, etc.)

https://api.iextrading.com/1.0/stock/cgc/news-image/8615998024490807 goes to https://storage.googleapis.com/iex/api/news/images/8615998024490807.png

all of the "image" which I "GET" from "news" results produce this anonymous caller error

I am using this: https://iextrading.com/developer/docs/#news

I am able to retrieve all other data points without any issues, specifically datetime, headline, source, url, and summary all work as expected.

**Comment by evancarter-iex** [comment]
This is working in IEXCloud (I spot tested a bunch of image links).

**Comment by godsart** [comment]
I don't understand your 'fix' or 'test' because these links still fail with access denied:
https://storage.googleapis.com/iex/api/news/images/5277617515197222.png
https://storage.googleapis.com/iex/api/news/images/8615998024490807.png

**Comment by evancarter-iex** [comment]
If you use:
https://cloud.iexapis.com/beta/stock/aapl/news?token=<TOKEN>
and then fetch the image links that are returned, it works. 

Let me know if you have any additional questions.

**Comment by weedstreet420** [comment]
@evancarter-iex 
We have the exact same issue. The LOGO endpoint is broken, and using the NEWS endpoint is not a solution because the image links are related to the articles, it is not always the company logo. We are looking for the official company logo, the same that should be returned by the LOGO endpoint.

Also, if you are looking for the logo of an OTC stock, you can't fetch the image from the NEWS endpoint because news are not supported for OTC stocks (but LOGO endpoint is)

Test with:
https://cloud.iexapis.com/beta/stock/SVVTF/logo

Returns:
`{"url":"https://storage.googleapis.com/iex/api/logos/SVVTF.png"}`

But the image URL returned by the API is broken:
https://storage.googleapis.com/iex/api/logos/SVVTF.png
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to iex/api/logos/SVVTF.png.
</Details>
</Error>
```

Please fix the LOGO endpoint!

**Comment by evancarter-iex** [comment]
@weedstreet420 please open a new issue if particular logos are busted on the logo endpoint. This was about the news endpoint. Thanks

**Comment by godsart** [comment]
Yes, please give me exact working urls according to your way for the
example broken links returned by api


https://storage.googleapis.com/iex/api/news/images/5277617515197222.png

https://storage.googleapis.com/iex/api/news/images/8615998024490807.png

**Comment by DocCaliban** [comment]
@evancarter-iex 
Your response seems to miss the point...  You said
> If you use:
> https://cloud.iexapis.com/beta/stock/aapl/news?token=TOKEN
> and then fetch the image links that are returned, it works.

But neither @godsart or I am calling https://cloud.iexapis.com/
We are calling https://api.iextrading.com/1.0/

This issue just started happening this year, and I really don't want to have to signup for https://iexcloud.io/ 
The open API works perfectly for my needs. 

Thanks

**Comment by joshuablackburn-iex** [comment]
@DocCaliban 
The old API will no longer have that data after June 1st. (https://iextrading.com/developer/docs/)

In order to continue offering more data and requested features, it required us to create a new platform with a new data provider. We built the new platform to be in parity with the old API to make transition as easy as possible. We are no longer supporting 3rd party data on the old API.

**Comment by DocCaliban** [comment]
> @DocCaliban
> The old API will no longer have that data after June 1st. (https://iextrading.com/developer/docs/)
> 
> In order to continue offering more data and requested features, it required us to create a new platform with a new data provider. We built the new platform to be in parity with the old API to make transition as easy as possible. We are no longer supporting 3rd party data on the old API.

Ahh makes sense now...  I had not read that it was being deprecated.  Thanks for the heads up!
