### ISSUE TITLE
Getting dividend amount into Google Sheets

### ISSUE THREAD

**Issue by dmikester1** [iexg/IEX-API#742]
## Summary
I am trying out the new IEX Cloud Beta.  I simply want to get the dividend amount into my Google Sheet.

## Details
I have inserted the following formula into my cell hoping to get just the dividend.  `=IMPORTDATA("https://cloud.iexapis.com/beta/stock/" & A3 & "/dividends/next/?filter=amount&token=xxxxx")`  A3 obviously points to a stock ticker.  This does not give me just the amount, but all the dividend results for that stock.  How can I pull out just the amount or any other single result?

### Date/time of issue
March 4, 2019

### API URL
https://cloud.iexapis.com/beta/stock/" & A3 & "/dividends/next/?filter=amount&token=xxxxx

### What you expected to happen
Get just the dividend amount for the stock

### What actually happened
Got all the dividend details for the stock

**Comment by kbeck1** [comment]
I have this problem as well when trying to pull a stock's ex-dividend and payment dates.

**Comment by dmikester1** [comment]
So I figured out a way to do this.  I don't really like how the index number is hard-coded in because anytime IEX changes the format of the json, it will break.  But here is the formula that I figured out to grab just the dividend amount, obviously adjust the index number at the very end to grab any of the other values.  I am also using the ImportJSON function which I imported from here: https://gist.github.com/chrislkeller/5719258

Formula:
`=INDEX(ImportJSON("https://cloud.iexapis.com/beta/stock/" & A4 & "/dividends/next/?token=pk_xxxxx", "", "noHeaders"), 5)`

**Comment by kbeck1** [comment]
I used [this modified version](https://github.com/bradjasper/ImportJSON/blob/d96de9cea38463048edaa60a1f60c64ad9dd1a5f/ImportJSON.gs) of the ImportJSON function, which allows you to select the values (which is important if you have a monthly dividend, as the IEX API will return more than one value).

This allows you to do something like so

`=IF(ISBLANK($A4),,ImportJSON("https://cloud.iexapis.com/beta/stock/"&$A4&"/dividends?token=xxxxxx", "/exDate[0]", "noHeaders"))`

or

`=IF(ISBLANK($A4),,ImportJSON("https://cloud.iexapis.com/beta/stock/"&$A4&"/dividends?token=xxxxxx", "/amount[0]", "noHeaders"))`

I think this method if more flexible than using a hard-coded index number. Thoughts?

**Comment by twoinvesting** [comment]
@dmikester1 Here are two importdata calls for Google Sheets that work:
`=importdata(https://cloud.iexapis.com/stable/data-points/aapl/LAST-DIVIDEND-AMOUNT?token="pk_123456789")`

`=importdata(https://cloud.iexapis.com/stable/stock/aapl/dividends?token="pk_123456789")`

@kbeck1 Thanks for the ImportJSON function above. I've found that using that function is faster than using many importdata calls in Google Sheets. I am running into some issues

The issue that I'm running into is that both the above importdata calls work for a company like AAPL, however, when trying to retrieve dividend data for M (Macy's), only the top importdata call works while the bottom one returns [].

Issues like this really make it hard to make a working spreadsheet since random stocks don't work.

Scott
