### ISSUE TITLE
History usage costs for daily data don't make sense

### ISSUE THREAD

**Issue by jonstelly** [iexg/IEX-API#780]
## Summary
The [historical API](https://iexcloud.io/docs/api/#historical-prices) usage cost for daily values seems a bit strange.  The cost for making a single day request with `chartByDay=true` has a usage cost of 2, where requesting a 1 month history that returns 19 days has a usage cost of 190 or 5 times higher than if I made 19 individual requests.

## Details

Based on this costing it seems like it would save me money if I were to make 19 `chartByDay` requests for each individual day instead of a single request for the month, but that's not just more complex for me, but I'm guessing it probably puts more strain on your servers too.

### API URL

`https://cloud.iexapis.com/beta/stock/SPY/chart/1m?token=???`
vs
`https://cloud.iexapis.com/beta/stock/SPY/chart/date/20190313?token=???&chartByDay=true`

### What you expected to happen

For bulk daily history API calls to have a reasonable usage cost.

**Comment by dsrapaport** [comment]
You have the optional query string parameter "chartCloseOnly=true" which should limit the data returned to date, close, volume and costs 2 instead of 10.

One caveat: I have been trying to get this to work properly, so that it only returns date, close, and volume (and no other data elements).  However, when I add "chartCloseOnly=true" to the URL, it also returns the additional fields "change", "changePercent", and "changeOverTime".

I opened a github issue shortly after you posted your issue here to see if this can be fixed and only return date, close, and volume when "chartCloseOnly=true" is used in the url.   This issue is [https://github.com/iexg/IEX-API/issues/781#issue-421210915](url)

**Comment by jonstelly** [comment]
Yeah, but I'm trying to get OHLCV so the close only doesn't work for my case.  Out of curiosity, where did you find mention of the filter parameter in your issue?  I don't see that on the docs anywhere.

**Comment by dsrapaport** [comment]
Hi Jon - It's in the cloud docs, specifically in the "Historical Prices" section, and is listed as the first "Query String Parameter" within that section.  

Go to the section here: [https://iexcloud.io/docs/api/#historical-prices](url)

Alternatively, just go to the iexcloud.io docs and search for "chartCloseOnly" and you will find it.

However, it still seems to be exhibiting the issue that I identified in [https://github.com/iexg/IEX-API/issues/781#issue-421210915](url) . I am not quite sure how to resolve it.

**Comment by evancarter-iex** [comment]
Closing this. #781 was fixed so the filter parameter should work now.
