### ISSUE TITLE
Saturday - I can't get a quote Friday

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#801]
## Summary
At the moment:
- In NY Friday, 23 PM
- In Paris Saturday, 4 am

I'm in Paris. I want to see yesterday's quotes for example JNJ.
1 attempt: 
https://cloud.iexapis.com/beta/stock/jnj/chart/1d?chartByDay=true&chartCloseOnly=true&chartLast=1&token=MY_TOKEN
result: A large list of quotes for the whole day by the minute.

1 attempt: 
https://cloud.iexapis.com/beta/stock/jnj/chart/1d?chartByDay=true&chartCloseOnly=true&chartLast=1&token=MY_TOKEN
result: 

```json
[{
"date":"20190322",
"minute":"15:59",
"label":"3:59 PM",
"high":137.1,
"low":136.86,
"average":136.975,
"volume":7488,
"notional":1025668.43,
"numberOfTrades":73,
"marketHigh":137.12,
"marketLow":136.86,
"marketAverage":136.933,
"marketVolume":186732,
"marketNotional":25569800.4275,
"marketNumberOfTrades":1083,
"open":137,
"close":136.91,
"marketOpen":136.98,
"marketClose":136.91,
"changeOverTime":-0.005106117171951968,
"marketChangeOverTime":-0.005866081994468031
}]
```
Okay, I'll get the last price, but I won't know the volume for the day.

3 attemp:

https://cloud.iexapis.com/beta/stock/jnj/chart/1m?chartByDay=true&chartCloseOnly=true&token=
result: 
```json
[....,{
"date":"2019-03-21",
"close":138.1,
"volume":5765119,
"change":0.81,
"changePercent":0.59,
"changeOverTime":0.010981}]
```

No data for yesterday :(

You need to give the daily data immediately after the market closes or after midnight in NY. Or something else. I do not understand how it is now formed. Can you tell?

**Comment by xxx44yyy** [comment]
Now I need to do: get all the minute quotes for yesterday, summarize the volume, get the last price. It's a strange decision.

**Comment by McQgit** [comment]
@xxx44yyy Have you looked at using the 'quote' endpoint instead of 'chart'?  That will have the daily volume and closing quote by around 4:30pm NY time.  It also has a 30day average volume.  The inconsistent results for the same request in your original post is a different problem.  But, perhaps quote would be better for you anyway?  Sorry if I misunderstand your requirement.

[https://iexcloud.io/docs/api/#quote]

**Comment by xxx44yyy** [comment]
> Sorry if I misunderstand your requirement.

@McQgit Thanks for answer. Sorry, I will ask easier: how can I get a **close price** and **volume** (for that day) any day, right after the market closes?

**Comment by McQgit** [comment]
@xxx44yyy  As I already said, use the 'quote' function:

[]https://iexcloud.io/docs/api/#quote

**Comment by xxx44yyy** [comment]
> @xxx44yyy As I already said, use the 'quote' function:
> 
> []https://iexcloud.io/docs/api/#quote

There is latestVolume, but no total volume for the entire day.

**Comment by McQgit** [comment]
@xxx44yyy  It is defined in the docs as the 'total market volume' - don't get hung up on the name.  All the 'latest' numbers for 'quote' aren't just the last trade.  Alas, the few I checked all were zero so that is a bug.  You should report that as a bug if no one from IEX sees that here.  Note the IEX V1 API has the day's volume in this field - it is a bug in the new Cloud Beta API.  So, you could use the older API 'quote' function until they get this sorted.

**Comment by xxx44yyy** [comment]
@McQgit Okay, thanks!

**Comment by evancarter-iex** [comment]
Closing this, since it was answered. Thanks @McQgit
