### ISSUE TITLE
Total (TOT) forget one dividend payout

### ISSUE THREAD

**Issue by xxx44yyy** [iexg/IEX-API#816]
## Summary

request: https://cloud.iexapis.com/beta/stock/tot/dividends/2y?token=
response:

```json
[
  {
    "exDate": "2019-03-18",
    "paymentDate": "2019-04-12",
    "recordDate": "2019-03-19",
    "declaredDate": "2018-10-26",
    "amount": 0.64,
    "flag": "No Change QoQ",
    "currency": "EUR",
    "description": "TOTAL Declares Quarterly Dividend of EUR 0.64 Per Share",
    "frequency": "Quarterly"
  },
  {
    "exDate": "2018-12-14",
    "paymentDate": "2019-01-17",
    "recordDate": "2018-12-17",
    "declaredDate": "2018-07-26",
    "amount": 0.64,
    "flag": "No Change QoQ",
    "currency": "EUR",
    "description": "TOTAL Declares Quarterly Dividend of EUR 0.64 Per Share",
    "frequency": "Quarterly"
  },
  {
    "exDate": "2018-09-25",
    "paymentDate": "2018-10-12",
    "recordDate": "0000-00-00",
    "declaredDate": "2018-04-26",
    "amount": 0.64,
    "flag": "Increase",
    "currency": "EUR",
    "description": "TOTAL Hikes Quarterly Dividend 3.23%",
    "frequency": "Quarterly"
  },
  {
    "exDate": "2018-03-15",
    "paymentDate": "2018-04-09",
    "recordDate": "2018-03-16",
    "declaredDate": "2017-10-27",
    "amount": 0.62,
    "flag": "No Change QoQ",
    "currency": "EUR",
    "description": "Total Declares Quarterly Dividend of EUR 0.62 Per Share",
    "frequency": "Quarterly"
  },
  {
    "exDate": "2017-12-15",
    "paymentDate": "2018-01-11",
    "recordDate": "2017-12-18",
    "declaredDate": "2017-07-27",
    "amount": 0.62,
    "flag": "No Change QoQ",
    "currency": "EUR",
    "description": "Total Declares Quarterly Dividend of EUR 0.62 Per Share",
    "frequency": "Quarterly"
  },
  {
    "exDate": "2017-09-21",
    "paymentDate": "2017-10-12",
    "recordDate": "2017-09-22",
    "declaredDate": "2017-04-27",
    "amount": 0.62,
    "flag": "Increase",
    "currency": "EUR",
    "description": "Total Declares Hikes Quarterly Dividend 1.64%",
    "frequency": "Quarterly"
  }
]
```

## Details

1. forget payment at 

> 6/7/2018 | Cash | 0.716 | -- | 6/8/2018 | 7/6/2018
> -- | -- | -- | -- | -- | --

see: [https://www.nasdaq.com/symbol/tot/dividend-history](https://www.nasdaq.com/symbol/tot/dividend-history)

2. see:

>  "recordDate": "0000-00-00",

![Снимок экрана 2019-03-27 в 2 59 24](https://user-images.githubusercontent.com/40538167/55041073-67b9cb00-503c-11e9-8757-3af2300c5181.png)

**Comment by evancarter-iex** [comment]
@theofficejackpot  
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is correct. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
