### ISSUE TITLE
Earnings Endpoint is not working

### ISSUE THREAD

**Issue by jordankendall86** [iexg/IEX-API#848]
## Summary
The earnings endpoint is not working using batch query

## Details
While using for example "https://api.iextrading.com/1.0/stock/tap/batch?types=earnings" the json returned is the following:
{"earnings":{}}
### Date/time of issue
April 9th, 2019 @ 9:55 AM PST

### API URL
https://api.iextrading.com/1.0/stock/tap/batch?types=earnings

### What you expected to happen
I would expect the earnings to show for the last four quarters

### What actually happened
I received the following result:
{"earnings":{}}

**Comment by evancarter-iex** [comment]
Please try this again with IEXCloud, https://iexcloud.io   The old api.iextrading.com is being deprecated in June.

**Comment by richardeschloss** [comment]
Also, I can add to this..I just tried this today and verified working but...(I have comments at the end):
single symbol: 
> (prod):  https://cloud.iexapis.com/stable/stock/aapl/earnings?token=[token]
> (sandbox):  https://sandbox.iexapis.com/stable/stock/aapl/earnings?token=[test_token]

batch:
> (prod): https://cloud.iexapis.com/stable/stock/market/batch?symbols=aapl,intc&types=earnings&last=4&token=[token]
> (sandbox): https://sandbox.iexapis.com/stable/stock/market/batch?symbols=aapl,intc&types=earnings&last=4&token=[test_token]

Now... for the buts.... 
1. I can use the *last* parameter to specify the number of quarters, but it seems like I can't get more than past 4 quarters. 
2. The docs say the last parameter can specify either quarters or years, but it's not obvious how to if I supply just a number. I would like to supply the parameter as a string: '5y', '1y' or '4q'. Otherwise, it's not clear to me when just the number 4 would represent "4 quarters" or "4 years".
