### ISSUE TITLE
ETFs missing dividends

### ISSUE THREAD

**Issue by hmTodd** [iexg/IEX-API#866]
Thanks for adding distribution data for ETFs.  I'm hoping that will include capital gains distributions and others as well as dividends.  Can anyone confirm this?

At this point it appears a number of symbols are missing dividends.  I quickly checked a few recent payers and found these missing:  HYLD, FCEF, PPTY, AGGE, INFR.   Is it safe to assume that the remaining funds will soon show up?

Related - Can we expect to see distribution data for CEFs soon?

Thanks,

**Comment by evancarter-iex** [comment]
These are pretty small funds that run these etf's. We will see what we can do.

**Comment by hmTodd** [comment]
Thanks. I understand priorities at this point in the game.  

That said, DIA is not insignificant and it's dividend from last Thursday is missing.  Also several from today (e.g. SPHD, SPLV, VRP, ...).  No reply necessary.  Just FYI.

**Comment by evancarter-iex** [comment]
@hmTodd You are correct on the updates, Ill look into that, that is something that should not be happening.

**Comment by evancarter-iex** [comment]
@hmTodd those dividends should be updated.

**Comment by evancarter-iex** [comment]
@hmTodd 
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is now there. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
