### ISSUE TITLE
Proper way to disconnect from IEX websocket server

### ISSUE THREAD

**Issue by yccheok** [iexg/IEX-API#87]
Currently, we are using Java + Android, to perform connection to IEX websocket server.

We are using the following class object, to perform connection.

https://gist.github.com/yccheok/16c07dfff9abf4881014bba8d35f531e

Whenever we re-create the class instance, we will ensure we perform the following cleanup using

    @Override
    public void disconnect() {
        synchronized (connectedMonitor) {
            //if (false == connected) {
            //    return;
            //}

            socket.disconnect();
        }
    }

However, we realize if we re-create the class instance for several times, we will start to observe some weird behavior.

A same stock quote with same timestamp, will be streamed multiple times, even we are pretty sure that we only call `socket.emit("subscribe", string);` one time. (We place a log just before we emit "subscribe" to IEX server. This is to observe we didn't send any extra `subscribe` to IEX server)

Here's an example of string we received in sequence.

> {"symbol":"MDLZ","price":42.595,"size":200,"time":1510691131559}
> {"symbol":"MDLZ","price":42.595,"size":200,"time":1510691131559}
> {"symbol":"MSFT","price":83.705,"size":200,"time":1510691133391}
> {"symbol":"MSFT","price":83.705,"size":200,"time":1510691133391}
> {"symbol":"MMM","price":229.37,"size":100,"time":1510691132525}
> {"symbol":"MMM","price":229.37,"size":100,"time":1510691132525}
> {"symbol":"MSFT","price":83.705,"size":200,"time":1510691133391}
> {"symbol":"MSFT","price":83.705,"size":200,"time":1510691133391}
> {"symbol":"MMM","price":229.37,"size":100,"time":1510691132525}
> {"symbol":"MMM","price":229.37,"size":100,"time":1510691132525}
> {"symbol":"GOOG","price":1026.06,"size":18,"time":1510691134582}
> {"symbol":"GOOG","price":1026.06,"size":18,"time":1510691134582}
> {"symbol":"SPGI","price":158.96,"size":100,"time":1510691135608}
> {"symbol":"SPGI","price":158.96,"size":100,"time":1510691135608}
> 

We even try to emit `unsubscribe` before we emit `subscribe`. But, that doesn't help.

    .on("connect", new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            synchronized (connectedMonitor) {
                connected = true;

                if (false == subscribes.isEmpty()) {
                    final String string = IEXWebSocketStockServer.toString(subscribes);
                    
                    // Server side cleanup?
                    socket.emit("unsubscribe", string);
                    socket.emit("subscribe", string);

I suspect previos class instance doesn't perform proper disconnection from IEX server, when the new class instance is re-created.

I was wondering, is there any additional thing we should emit to IEX server, before calling `sockect.disconnect` ?

Thanks.

**Comment by jcape** [comment]
@yccheok Have you confirmed that you're actually disconnecting the socket? Otherwise I've identified two scenarios where there could be seemingly duplicate data on the last feed:

 1. Two trades that happen within the same millisecond, at the same price. This may seem unlikely, but it actually happens very frequently. For example, two sellers post 100 shares each of MMM. A single buyer comes in trying to match for 1000 shares. The buyer will get filled for 200 shares, each seller will get filled for 100 shares. On the tape, this is printed as two trades with the same timestamp, each for 100 shares. Unfortunately, there isn't enough information to identify this on the last websocket. The vast majority of the time, this is the source of seemingly duplicate data on LAST.

2. Actual duplicate data on the LAST feed. This is an unfortunate side-effect of our use of sockets.io, and eliminating it is requirement no. 2 of the new SSE stream (the first being "SSE stream"). We're trying to get SSE out the door this month, and LAST is the second feed that will be available over SSE.

In the interim, I'm asking around internally to see if we can get a trade-ID added to LAST, which would allow you to distinguish scenario 1 from scenario 2 (and apply a post-hoc corrections for 2).

**Comment by yccheok** [comment]
@jcape 

From my side, whenever I try to establish another connection, I had ensured previous `socket.disconnect();` is called (By placing some logging around)

I also hold suspicion on client side. Is there anything I should `emit`, before calling `socket.disconnect();`  ?

**Comment by jcape** [comment]
If you're actually dropping the TCP connection, re-connecting and re-subscribing shouldn't cause duplicates to arrive (other than for the reasons stated).

If you're concerned, you can always emit an unsubscribe for anything you're subscribed to before you disconnect---at the very least, you should be able to leave the socket open and sub/unsub things as needed.

**Comment by joshuablackburn-iex** [comment]
IEX Cloud provides SSE streaming.
