### ISSUE TITLE
IEX Cloud News endpoint returns invalid image urls

### ISSUE THREAD

**Issue by mikezliu** [iexg/IEX-API#879]
## Summary

Some of the articles returned by the news endpoint point to a non existent image hosted on IEX

## Details

When accessing the news endpoint at (example): https://cloud.iexapis.com/v1/stock/MSFT/news/last/20?token=pk***

Some of the image urls point to non existent.  For example, the above link returns:

{
        "datetime": 1555570960000,
        "headline": "Microsoft promises biggest ever presence at Xbox E3 2019 press conference in June",
        "source": "Moneycontrol",
        "url": "https://cloud.iexapis.com/beta/news/article/bf32e09e-a998-4352-b18d-40caac1f2cb4",
        "summary": "Microsoft will follow up the keynote with a special episode of Inside Xbox, which will air on Monday, Jun 10th at 06.00 p.m. EDT.",
        "related": "MSFT",
        "image": "https://cloud.iexapis.com/beta/news/image/bf32e09e-a998-4352-b18d-40caac1f2cb4",
        "lang": "en",
        "hasPaywall": false
    },

If you follow the image link (https://cloud.iexapis.com/beta/news/image/bf32e09e-a998-4352-b18d-40caac1f2cb4), it will point to 404 Not Found

### Date/time of issue

Now (7:26 AM GMT)

### What you expected to happen

https://cloud.iexapis.com/v1/stock/MSFT/news/last/20?token=pk***

### What actually happened

The image url returns a 404 Not Found

https://cloud.iexapis.com/beta/news/image/bf32e09e-a998-4352-b18d-40caac1f2cb4

### Other Information (sample code, links, etc.)

Happens for other links as well

**Comment by bclous** [comment]
It looks like a change was just made regarding this issue and I think it should be reverted.  Previously, up to 70% of the urls for news article images returned 404 not found.  This is obviously not ideal but it allowed us to use our own placeholder image with our own color scheme and branding. 

Now, it appears that instead of a 404 Not Found, these links are returning an IEX Cloud white branded placeholder image.  Effectively, instead of fixing the reason most of the links don't work, you've just redirected to your own placeholder image instead of letting us use our own, and taken away the ability for us to be able to tell if there is in fact a real image associated with the article. 

This wouldn't be the end of the world if most of the links sent back an image relating to the article but as I mentioned, most do not.  As we are paying for the IEX Cloud API, we shouldn't have to have the IEX Cloud placeholder image displayed all over our applications when we use the News API.

Returning a 404 not found was way more desirable than what has just been implemented.

**Comment by lars670** [comment]
@IEX, what will the decision be here?
Will you revert to 404´s or stick the new principle of IEX images en mass
We hope for the previous approach, otherwise we have to do a redo and find a way to somehow recognize and filter the IEX image.

**Comment by hopskotia** [comment]
i realize this is a separate service issue, but the same issue occurs with many of the actual news source URLs as well.  a remarkable numbers of links are "not found" for both images and source URLs.  This makes the service fairly unreliable for the time except for the headlines.   perhaps an issue with the IEX Redirect service?

**Comment by maykonmeneghel** [comment]
Any solution?
