### ISSUE TITLE
IEX Cloud SSE "Request-URI Too Large" error

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#881]
Hi,

What is the max length for SSE request URI? I tried to connect to ``tops`` endpoint with about 6000 symbols and I got "Request-URI Too Large" error. In documentation you say that Firehose is available for scale users. Is it available for other users too? If not how we can subscribe to many symbols, all USA symbols for example?

Thanks,
Gabriel

**Comment by evancarter-iex** [comment]
I believe the limit is roughly 2000 characters. In order to get Firehose you need to upgrade to scale.

**Comment by gabrieldodan** [comment]
@evancarter-iex with Grow plan , as a workaround , i would be allowed to subscribe to ``tops`` using multiple connections ?

**Comment by yccheok** [comment]
@evancarter-iex Same issues here.

Previously, we have no issue, to retrieve almost all symbols using WebSocket - https://github.com/iexg/IEX-API/issues/55

However, by using SSE

```
function connect(symbols) {
    stream = request({
        url: 'https://cloud-sse.iexapis.com/beta/last?token=???&symbols=' + symbols,
        headers: {
            'Content-Type': 'text/event-stream'
        }
    })
}

```

It seems that there can be limitation on the length of request URL, as described by @gabrieldodan 

Since, we can only afford the Launch plan. I was wondering, for workaround, is it recommend to have multiple SSE connection from single server, with every connection string length will less than 2000 ?

Thanks.

**Comment by evancarter-iex** [comment]
@yccheok per documentation: https://iexcloud.io/docs/api/#streaming "Currently SSE requests are limited to 50 symbols per connection, but you can have multiple connections."
