### ISSUE TITLE
SSE stream disconnection

### ISSUE THREAD

**Issue by gabrieldodan** [iexg/IEX-API#900]
I am connecting to ``tops`` stream while the market is closed and after a few seconds I am disconnected. How can i keep the connection alive?

Thanks!
Gabriel

**Comment by evancarter-iex** [comment]
@gabrieldodan How are you connecting?

**Comment by gabrieldodan** [comment]
@evancarter-iex using nodejs, see below 

```
let stream = request({
    url: 'https://cloud-sse.iexapis.com/v1/tops?token=<token>&symbols=msft',
    headers: {
    	'Content-Type': 'text/event-stream'
    }
});
```

**Comment by evancarter-iex** [comment]
@gabrieldodan Is it just that section of code or are you using the full code example in the docs?

**Comment by gabrieldodan** [comment]
@evancarter-iex i have tested with your example code in the docs, just URL differ. And I am disconnected. 

BTW, your example code is wrong. In case of re-connection events handlers are not attached again....

**Comment by gabrieldodan** [comment]
@evancarter-iex any update on this issue? I am disconnected even when market is open...

**Comment by mikezliu** [comment]
I'm using firehose to stream all symbols, and it seems to disconnect after 2-3 mins of inactivity even when market is trading (seems to happen during extended hours). The problem is that when reconnecting, the first connect will send you a full snapshot and will use up ~10k messages. Doing some approximate math, this can waste about 200 million messages a month on worst case, or around 150 million messages a month if it doesn't disconnect during market trading hours. Is there something we can do to mitigate this issue? Ideally when streaming all symbols, it shouldn't disconnect even after 2-3 mins of inactivity. This is not a big issue when streaming just 1 symbol, since you can reconnect and not waste so many messages.

**Comment by evancarter-iex** [comment]
@mikezliu We are in the process of fixing a series of issues with SSE, including the snapshot, disconnection and other issues. I'll let you know when its deployed.

**Comment by gabrieldodan** [comment]
@evancarter-iex any update on this issue? has been fixed?

Thanks

**Comment by evancarter-iex** [comment]
@gabrieldodan We arent seeing issues at this point on our end. Can you email support@iexcloud.io so we can help track down any issues you are still having?
