### ISSUE TITLE
[Data] Closed End Fund dividends not available

### ISSUE THREAD

**Issue by chortleflux** [iexg/IEX-API#921]
**Clearly describe the data problem**
It appears that no dividend data is available for closed end mutual funds.  Dividends for closed end mutual funds should be available.  I have checked a handful of them, and none show any dividend history at all.

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/NVG/dividends?token=XXXXXX&range=1m

**What time did the problem occur (including timezone)?**
1:00pm CST

**What is the expected behavior?**
For NVG above, there should be a dividend with Ex Date 2019-04-12 and amount equal to $0.0655.

**What are the steps to reproduce**
Use url above.

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**
Are there plans / estimates for when closed end fund dividends might be available?

**Comment by evancarter-iex** [comment]
@chortleflux   
We’re reaching out to let you know that we've significantly expanded and improved our dividends data offering. 

IEX Cloud now covers an additional 31,000+ securities and an additional 465,000+ dividends records. These improvements mean that you can now access a more up-to-date and robust selection of data through our dividends endpoint. 

Thank you for providing your feedback on GitHub. Your comments are critical to our roadmap and informing what we build next. 

We will now close this ticket since the data is now present. If you have any other questions or additional comments, please let us know by emailing support@iexcloud.io.
