### ISSUE TITLE
[Issue] Some APIs return None, some return 404

### ISSUE THREAD

**Issue by professorDante** [iexg/IEX-API#972]
**Clearly describe the problem**

Total inconsistency with what calls return when they have no results. Some return empty Json, some just 404.
**What time did the problem occur? (with timezone)**
Not relevant.

**What is the expected behavior?**

APIs should return consistent behaviour. At the moment they are all seemingly different.
**Your environment (e.g. browser, OS, API version, language):**

**API URL (if applicable)**
1. https://sandbox.iexapis.com/beta/stock/IWM/earnings/4?token=999

This will return empty json or None.

2. https://sandbox.iexapis.com/beta/stock/IWM/price-target?token=999

This will return a 404. This makes it really painful to code efficiently.

**What are the steps to reproduce the bug?**

**Additional context**

**Comment by joshuablackburn-iex** [comment]
This is carried over from our old API. Based on overwhelming user feedback, endpoints that return arrays will return an empty array when no data is available. Endpoints that return an object return a null when no data is available. The null is translated into no data available, which is a 404. The 404 error may be a bit harsh and is something we can look at in a new version. We used to return {}, but a number of developers, specifically java and scala developers, wanted null. It has therefore been this way since early last year.
